/*
 * generated by Xtext 2.9.1
 */
package no.hal.learning.exercise.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XerciseStandaloneSetup extends XerciseStandaloneSetupGenerated {

	def static void doSetup() {
		new XerciseStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
