/*
 * generated by Xtext
 */
package no.hal.jex.jextest.ui.contentassist

import no.hal.jex.jextest.ui.contentassist.AbstractJexTestProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class JexTestProposalProvider extends AbstractJexTestProposalProvider {
}
