/*
 * generated by Xtext 2.10.0
 */
package no.hal.learning.exercise.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXerciseScopeProvider extends DelegatingScopeProvider {
}
