/**
 * generated by Xtext 2.9.1
 */
package no.hal.learning.exercise.xtext;

import no.hal.learning.exercise.xtext.XerciseStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XerciseStandaloneSetup extends XerciseStandaloneSetupGenerated {
  public static void doSetup() {
    XerciseStandaloneSetup _xerciseStandaloneSetup = new XerciseStandaloneSetup();
    _xerciseStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
