/*
 * generated by Xtext
 */
package no.hal.emfs.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XemfsUiModule extends no.hal.emfs.xtext.ui.AbstractXemfsUiModule {
	public XemfsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
