<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="emfs" nsURI="platform:/plugin/no.hal.emfs/model/emfs.ecore"
    nsPrefix="emfs">
  <eClassifiers xsi:type="ecore:EClass" name="EmfsResource" eSuperTypes="#//TagsOwner #//PropertyOwner">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//EmfsContainer"
        eOpposite="#//EmfsContainer/resources"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagsOwner">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eRef" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfsContainer" eSuperTypes="#//EmfsResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//EmfsResource" containment="true" eOpposite="#//EmfsResource/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//EmfsContainerContentProvider"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfsContainerContentProvider" abstract="true">
    <eOperations name="importContent" upperBound="-1" eType="#//EmfsResource">
      <eParameters name="importSupport" eType="#//ExportSupport"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ExportSupport" instanceClassName="no.hal.emfs.exporter.ExportSupport"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmfsResourcesRef" eSuperTypes="#//EmfsContainerContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//EmfsResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GitContentProvider" eSuperTypes="#//EmfsContainerContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gitRef" eType="#//GitContentRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfsFile" eSuperTypes="#//EmfsResource #//EmfsFileContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//EmfsFileContentProvider"
        containment="true" eOpposite="#//EmfsFileContentProvider/file"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" upperBound="-1"
        eType="#//EmfsFileContentProvider" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfsFileContentProvider" abstract="true"
      interface="true">
    <eOperations name="getInputStream" eType="#//EInputStream">
      <eParameters name="options" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getOutputStream" eType="#//EOutputStream">
      <eParameters name="options" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" eType="#//EmfsFile"
        eOpposite="#//EmfsFile/contentProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EInputStream" instanceClassName="java.io.InputStream"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EOutputStream" instanceClassName="java.io.OutputStream"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractBytesContentProvider" abstract="true"
      eSuperTypes="#//EmfsFileContentProvider">
    <eOperations name="getByteContents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eOperations name="setByteContents">
      <eParameters name="contents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ByteArrayContentProvider" eSuperTypes="#//AbstractBytesContentProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteContents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStringContentProvider" abstract="true"
      eSuperTypes="#//AbstractBytesContentProvider #//AbstractStringContents"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringContentProvider" eSuperTypes="#//AbstractStringContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringContents" upperBound="-1"
        eType="#//AbstractStringContents" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStringContents" abstract="true"
      eSuperTypes="#//TagsOwner #//PropertyOwner">
    <eOperations name="getStringContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="setStringContent">
      <eParameters name="contents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="accumulate">
      <eGenericType eTypeParameter="#//AbstractStringContents/accumulate/A"/>
      <eTypeParameters name="A"/>
      <eParameters name="accumulator">
        <eGenericType eClassifier="#//EStringAccumulator">
          <eTypeArguments eTypeParameter="#//AbstractStringContents/accumulate/A"/>
        </eGenericType>
      </eParameters>
      <eParameters name="initialValue">
        <eGenericType eTypeParameter="#//AbstractStringContents/accumulate/A"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EStringAccumulator" instanceClassName="no.hal.emfs.util.StringAccumulator"
      serializable="false">
    <eTypeParameters name="A"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerbatimStringContents" eSuperTypes="#//AbstractStringContents">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValueString" eSuperTypes="#//AbstractStringContents">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WrappingStringContentProvider" eSuperTypes="#//EmfsFileContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prefix" eType="#//AbstractStringContents"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//EmfsFileContentProvider"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//AbstractStringContents"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractURLContentProvider" abstract="true"
      eSuperTypes="#//EmfsFileContentProvider">
    <eOperations name="getUrlString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URLContentProvider" eSuperTypes="#//AbstractURLContentProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GitURLContentProvider" eSuperTypes="#//AbstractURLContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gitRef" eType="#//GitContentRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GitRepoRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remoteString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GitContentRef" eSuperTypes="#//GitRepoRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CachingContentProvider" eSuperTypes="#//EmfsFileContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//EmfsFileContentProvider"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cache" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DotClasspathFileContentProvider" eSuperTypes="#//AbstractStringContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//AbstractClasspathEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractClasspathEntry" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ClasspathEntryKind"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="platform:/plugin/no.hal.emfs/model/emfs.ecore">
        <details key="java" value="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/J2SE-${major}.${minor}"/>
        <details key="junit" value="org.eclipse.jdt.junit.JUNIT_CONTAINER/${major}"/>
        <details key="plugins" value="org.eclipse.pde.core.requiredPlugins"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClasspathEntryKind">
    <eLiterals name="src" literal="src"/>
    <eLiterals name="output" value="1" literal="output"/>
    <eLiterals name="lib" value="2" literal="lib"/>
    <eLiterals name="con" value="3" literal="con"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClasspathEntry" eSuperTypes="#//AbstractClasspathEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitKind" eType="#//ClasspathEntryKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="absolute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="major" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DotProjectFileContentProvider" eSuperTypes="#//AbstractStringContentProvider">
    <eAnnotations source="org.eclipse.core.resources.natures">
      <details key="java" value="org.eclipse.jdt.core.javanature"/>
      <details key="pde" value="org.eclipse.pde.PluginNature"/>
    </eAnnotations>
    <eAnnotations source="org.eclipse.core.resources.builders">
      <details key="java" value="org.eclipse.jdt.core.javabuilder"/>
      <details key="pde" value="org.eclipse.pde.ManifestBuilder,org.eclipse.pde.SchemaBuilder"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keys" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedResources" upperBound="-1"
        eType="#//EmfsResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlStringContents" eSuperTypes="#//AbstractStringContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//XmlElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlContents">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//XmlElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="post" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlPIElement" eSuperTypes="#//XmlElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//XmlAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlTagElement" eSuperTypes="#//XmlElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MatchingEndTag"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startTag" eType="#//XmlTag"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//XmlContents" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//XmlAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfResourceStringContents" eSuperTypes="#//AbstractStringContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
