<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="exercise" nsURI="platform:/plugin/no.hal.learning.exercise.model/model/exercise.ecore"
    nsPrefix="exercise">
  <eClassifiers xsi:type="ecore:EClass" name="Exercise">
    <eOperations name="createProposals" eType="#//ExerciseProposals"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//AbstractExercisePart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExerciseProposals">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exercise" eType="#//Exercise"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proposals" upperBound="-1"
        eType="#//ExercisePartProposals" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allProposals" upperBound="-1"
        volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Proposal">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractExercisePart" abstract="true">
    <eOperations name="getTasks" upperBound="-1" eType="#//AbstractTask"/>
    <eOperations name="getTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="createProposals" eType="#//ExercisePartProposals"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExercisePartProposals">
    <eStructuralFeatures xsi:type="ecore:EReference" name="proposals" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//Proposal">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exercisePart" eType="#//ExercisePart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExercisePartRef" eSuperTypes="#//AbstractExercisePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="partRef" eType="#//ExercisePart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExercisePart" eSuperTypes="#//AbstractExercisePart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//AbstractTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTask" abstract="true">
    <eOperations name="getA" eType="#//Answer"/>
    <eOperations name="getQ" eType="#//Question"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskRef" eSuperTypes="#//AbstractTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskRef" eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//AbstractTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="q" eType="#//Question"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" eType="#//Answer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringQuestion" eSuperTypes="#//Question">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Answer" abstract="true">
    <eOperations name="accept" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject">
      <eParameters name="proposal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="proposal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="createProposal">
      <eGenericType eClassifier="#//Proposal">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proposal">
    <eTypeParameters name="A">
      <eBounds eClassifier="#//Answer"/>
    </eTypeParameters>
    <eOperations name="getProposal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eOperations name="accept" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" eType="#//Question"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answer">
      <eGenericType eTypeParameter="#//Proposal/A"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskAnswer" eSuperTypes="#//Answer">
    <eOperations name="acceptEvent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="event" eType="#//TaskEvent"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskProposal">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//TaskAnswer"/>
    </eTypeParameters>
    <eOperations name="getText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="addTaskEvent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="taskEvent" eType="#//TaskEvent"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proof" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attemptCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attempts" upperBound="-1"
        eType="#//TaskEvent" containment="true" eOpposite="#//TaskEvent/proposal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="performedCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eGenericSuperTypes eClassifier="#//Proposal">
      <eTypeArguments eTypeParameter="#//TaskProposal/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskEvent" eSuperTypes="fv.ecore#//EFeatureObject">
    <eOperations name="getText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proposal" eOpposite="#//TaskProposal/attempts">
      <eGenericType eClassifier="#//TaskProposal">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="#//ETimestamp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="-1">
      <eAnnotations source="no.hal.learning.exercise.views.ExerciseView">
        <details key="dashes" value="SOLID"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ETimestamp" instanceClassName="long"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringEditTaskProposal">
    <eTypeParameters name="A">
      <eBounds eClassifier="#//StringEditAnswer"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//TaskProposal">
      <eTypeArguments eTypeParameter="#//StringEditTaskProposal/A"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringEditAnswer" abstract="true" eSuperTypes="#//TaskAnswer">
    <eOperations name="getEditorPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStringEditEvent" eSuperTypes="#//TaskEvent">
    <eOperations name="getString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="createStringEdit" eType="#//AbstractStringEdit">
      <eParameters name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="lastEvent" eType="#//AbstractStringEditEvent"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edit" eType="#//AbstractStringEdit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="markers" upperBound="-1"
        eType="#//MarkerInfo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStringEdit" abstract="true">
    <eOperations name="getString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="initStringEdit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="lastEdit" eType="#//AbstractStringEdit"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeStringEdit" abstract="true"
      eSuperTypes="#//AbstractStringEdit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edit" eType="#//AbstractStringEdit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringEdit" eSuperTypes="#//AbstractStringEdit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storedString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaceSubstringEdit" eSuperTypes="#//StringEdit #//RelativeStringEdit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarkerInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="no.hal.learning.exercise.MarkerInfo">
        <details key="valueClass" value="org.eclipse.core.resources.IMarker"/>
        <details key="fieldPattern" value="SEVERITY_.*"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
