/*
 * generated by Xtext 2.10.0
 */
package no.hal.learning.exercise.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import no.hal.learning.exercise.xtext.ide.contentassist.antlr.internal.InternalXerciseParser;
import no.hal.learning.exercise.xtext.services.XerciseGrammarAccess;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class XerciseParser extends AbstractContentAssistParser {

	@Inject
	private XerciseGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalXerciseParser createParser() {
		InternalXerciseParser result = new InternalXerciseParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getExerciseAccess().getAlternatives_2(), "rule__Exercise__Alternatives_2");
					put(grammarAccess.getAbstractExercisePartAccess().getAlternatives(), "rule__AbstractExercisePart__Alternatives");
					put(grammarAccess.getAbstractTaskAccess().getAlternatives(), "rule__AbstractTask__Alternatives");
					put(grammarAccess.getAnswerAccess().getAlternatives(), "rule__Answer__Alternatives");
					put(grammarAccess.getSimpleAnswerAccess().getAlternatives(), "rule__SimpleAnswer__Alternatives");
					put(grammarAccess.getBooleanAnswerAccess().getAlternatives_1(), "rule__BooleanAnswer__Alternatives_1");
					put(grammarAccess.getBooleanAnswerAccess().getValueAlternatives_1_0_0(), "rule__BooleanAnswer__ValueAlternatives_1_0_0");
					put(grammarAccess.getBooleanAnswerAccess().getAlternatives_1_1(), "rule__BooleanAnswer__Alternatives_1_1");
					put(grammarAccess.getOptionsAnswerAccess().getAlternatives(), "rule__OptionsAnswer__Alternatives");
					put(grammarAccess.getSingleOptionsAnswerAccess().getAlternatives(), "rule__SingleOptionsAnswer__Alternatives");
					put(grammarAccess.getSingleListOptionAccess().getAlternatives_0(), "rule__SingleListOption__Alternatives_0");
					put(grammarAccess.getSingleListOptionAccess().getAlternatives_0_0(), "rule__SingleListOption__Alternatives_0_0");
					put(grammarAccess.getTaskAnswerAccess().getAlternatives(), "rule__TaskAnswer__Alternatives");
					put(grammarAccess.getPerspectiveTaskAnswerAccess().getActionAlternatives_2_1_1_0(), "rule__PerspectiveTaskAnswer__ActionAlternatives_2_1_1_0");
					put(grammarAccess.getPartTaskAnswerAccess().getActionAlternatives_2_1_1_0(), "rule__PartTaskAnswer__ActionAlternatives_2_1_1_0");
					put(grammarAccess.getCommandExecutionAnswerAccess().getActionAlternatives_2_1_1_0(), "rule__CommandExecutionAnswer__ActionAlternatives_2_1_1_0");
					put(grammarAccess.getDebugEventAnswerAccess().getActionAlternatives_2_1_1_0(), "rule__DebugEventAnswer__ActionAlternatives_2_1_1_0");
					put(grammarAccess.getExerciseAccess().getGroup(), "rule__Exercise__Group__0");
					put(grammarAccess.getExerciseAccess().getGroup_2_0(), "rule__Exercise__Group_2_0__0");
					put(grammarAccess.getQNameAccess().getGroup(), "rule__QName__Group__0");
					put(grammarAccess.getQNameAccess().getGroup_1(), "rule__QName__Group_1__0");
					put(grammarAccess.getExercisePartAccess().getGroup(), "rule__ExercisePart__Group__0");
					put(grammarAccess.getExercisePartRefAccess().getGroup(), "rule__ExercisePartRef__Group__0");
					put(grammarAccess.getAnonymousExercisePartAccess().getGroup(), "rule__AnonymousExercisePart__Group__0");
					put(grammarAccess.getTaskRefAccess().getGroup(), "rule__TaskRef__Group__0");
					put(grammarAccess.getTaskAccess().getGroup(), "rule__Task__Group__0");
					put(grammarAccess.getStringAnswerAccess().getGroup(), "rule__StringAnswer__Group__0");
					put(grammarAccess.getRegexAnswerAccess().getGroup(), "rule__RegexAnswer__Group__0");
					put(grammarAccess.getNumberAnswerAccess().getGroup(), "rule__NumberAnswer__Group__0");
					put(grammarAccess.getNumberAnswerAccess().getGroup_1(), "rule__NumberAnswer__Group_1__0");
					put(grammarAccess.getEDoubleObjectAccess().getGroup(), "rule__EDoubleObject__Group__0");
					put(grammarAccess.getEDoubleObjectAccess().getGroup_1(), "rule__EDoubleObject__Group_1__0");
					put(grammarAccess.getBooleanAnswerAccess().getGroup(), "rule__BooleanAnswer__Group__0");
					put(grammarAccess.getSingleBoxOptionAccess().getGroup(), "rule__SingleBoxOption__Group__0");
					put(grammarAccess.getSingleListOptionAccess().getGroup(), "rule__SingleListOption__Group__0");
					put(grammarAccess.getManyOptionAccess().getGroup(), "rule__ManyOption__Group__0");
					put(grammarAccess.getJunitTestAnswerAccess().getGroup(), "rule__JunitTestAnswer__Group__0");
					put(grammarAccess.getJunitTestAnswerAccess().getGroup_2(), "rule__JunitTestAnswer__Group_2__0");
					put(grammarAccess.getJunitTestAnswerAccess().getGroup_2_2(), "rule__JunitTestAnswer__Group_2_2__0");
					put(grammarAccess.getJdtSourceEditAnswerAccess().getGroup(), "rule__JdtSourceEditAnswer__Group__0");
					put(grammarAccess.getJdtSourceEditAnswerAccess().getGroup_3(), "rule__JdtSourceEditAnswer__Group_3__0");
					put(grammarAccess.getJdtSourceEditAnswerAccess().getGroup_3_2(), "rule__JdtSourceEditAnswer__Group_3_2__0");
					put(grammarAccess.getJdtLaunchAnswerAccess().getGroup(), "rule__JdtLaunchAnswer__Group__0");
					put(grammarAccess.getPerspectiveTaskAnswerAccess().getGroup(), "rule__PerspectiveTaskAnswer__Group__0");
					put(grammarAccess.getPerspectiveTaskAnswerAccess().getGroup_2(), "rule__PerspectiveTaskAnswer__Group_2__0");
					put(grammarAccess.getPerspectiveTaskAnswerAccess().getGroup_2_1(), "rule__PerspectiveTaskAnswer__Group_2_1__0");
					put(grammarAccess.getPartTaskAnswerAccess().getGroup(), "rule__PartTaskAnswer__Group__0");
					put(grammarAccess.getPartTaskAnswerAccess().getGroup_2(), "rule__PartTaskAnswer__Group_2__0");
					put(grammarAccess.getPartTaskAnswerAccess().getGroup_2_1(), "rule__PartTaskAnswer__Group_2_1__0");
					put(grammarAccess.getCommandExecutionAnswerAccess().getGroup(), "rule__CommandExecutionAnswer__Group__0");
					put(grammarAccess.getCommandExecutionAnswerAccess().getGroup_2(), "rule__CommandExecutionAnswer__Group_2__0");
					put(grammarAccess.getCommandExecutionAnswerAccess().getGroup_2_1(), "rule__CommandExecutionAnswer__Group_2_1__0");
					put(grammarAccess.getDebugEventAnswerAccess().getGroup(), "rule__DebugEventAnswer__Group__0");
					put(grammarAccess.getDebugEventAnswerAccess().getGroup_2(), "rule__DebugEventAnswer__Group_2__0");
					put(grammarAccess.getDebugEventAnswerAccess().getGroup_2_1(), "rule__DebugEventAnswer__Group_2_1__0");
					put(grammarAccess.getExerciseAccess().getNameAssignment_2_0_0(), "rule__Exercise__NameAssignment_2_0_0");
					put(grammarAccess.getExerciseAccess().getTitleAssignment_2_0_1(), "rule__Exercise__TitleAssignment_2_0_1");
					put(grammarAccess.getExerciseAccess().getPartsAssignment_2_0_2(), "rule__Exercise__PartsAssignment_2_0_2");
					put(grammarAccess.getExerciseAccess().getPartsAssignment_2_1(), "rule__Exercise__PartsAssignment_2_1");
					put(grammarAccess.getExercisePartAccess().getNameAssignment_1(), "rule__ExercisePart__NameAssignment_1");
					put(grammarAccess.getExercisePartAccess().getTitleAssignment_2(), "rule__ExercisePart__TitleAssignment_2");
					put(grammarAccess.getExercisePartAccess().getTasksAssignment_3(), "rule__ExercisePart__TasksAssignment_3");
					put(grammarAccess.getExercisePartRefAccess().getPartRefAssignment_2(), "rule__ExercisePartRef__PartRefAssignment_2");
					put(grammarAccess.getAnonymousExercisePartAccess().getTasksAssignment_1(), "rule__AnonymousExercisePart__TasksAssignment_1");
					put(grammarAccess.getTaskRefAccess().getTaskRefAssignment_1(), "rule__TaskRef__TaskRefAssignment_1");
					put(grammarAccess.getTaskAccess().getNameAssignment_0(), "rule__Task__NameAssignment_0");
					put(grammarAccess.getTaskAccess().getQAssignment_1(), "rule__Task__QAssignment_1");
					put(grammarAccess.getTaskAccess().getAAssignment_2(), "rule__Task__AAssignment_2");
					put(grammarAccess.getStringQuestionAccess().getQuestionAssignment(), "rule__StringQuestion__QuestionAssignment");
					put(grammarAccess.getStringAnswerAccess().getValueAssignment_0(), "rule__StringAnswer__ValueAssignment_0");
					put(grammarAccess.getStringAnswerAccess().getIgnoreCaseAssignment_1(), "rule__StringAnswer__IgnoreCaseAssignment_1");
					put(grammarAccess.getRegexAnswerAccess().getRegexpAssignment_0(), "rule__RegexAnswer__RegexpAssignment_0");
					put(grammarAccess.getRegexAnswerAccess().getValueAssignment_1(), "rule__RegexAnswer__ValueAssignment_1");
					put(grammarAccess.getRegexAnswerAccess().getIgnoreCaseAssignment_3(), "rule__RegexAnswer__IgnoreCaseAssignment_3");
					put(grammarAccess.getNumberAnswerAccess().getValueAssignment_0(), "rule__NumberAnswer__ValueAssignment_0");
					put(grammarAccess.getNumberAnswerAccess().getErrorMarginAssignment_1_1(), "rule__NumberAnswer__ErrorMarginAssignment_1_1");
					put(grammarAccess.getBooleanAnswerAccess().getValueAssignment_1_0(), "rule__BooleanAnswer__ValueAssignment_1_0");
					put(grammarAccess.getSingleBoxOptionsAnswerAccess().getOptionsAssignment(), "rule__SingleBoxOptionsAnswer__OptionsAssignment");
					put(grammarAccess.getSingleBoxOptionAccess().getCorrectAssignment_1(), "rule__SingleBoxOption__CorrectAssignment_1");
					put(grammarAccess.getSingleBoxOptionAccess().getOptionAssignment_3(), "rule__SingleBoxOption__OptionAssignment_3");
					put(grammarAccess.getSingleListOptionsAnswerAccess().getOptionsAssignment(), "rule__SingleListOptionsAnswer__OptionsAssignment");
					put(grammarAccess.getSingleListOptionAccess().getCorrectAssignment_0_1(), "rule__SingleListOption__CorrectAssignment_0_1");
					put(grammarAccess.getSingleListOptionAccess().getOptionAssignment_1(), "rule__SingleListOption__OptionAssignment_1");
					put(grammarAccess.getManyOptionsAnswerAccess().getOptionsAssignment(), "rule__ManyOptionsAnswer__OptionsAssignment");
					put(grammarAccess.getManyOptionAccess().getCorrectAssignment_1(), "rule__ManyOption__CorrectAssignment_1");
					put(grammarAccess.getManyOptionAccess().getOptionAssignment_3(), "rule__ManyOption__OptionAssignment_3");
					put(grammarAccess.getJunitTestAnswerAccess().getTestRunNameAssignment_1(), "rule__JunitTestAnswer__TestRunNameAssignment_1");
					put(grammarAccess.getJunitTestAnswerAccess().getMethodNamesAssignment_2_1(), "rule__JunitTestAnswer__MethodNamesAssignment_2_1");
					put(grammarAccess.getJunitTestAnswerAccess().getMethodNamesAssignment_2_2_1(), "rule__JunitTestAnswer__MethodNamesAssignment_2_2_1");
					put(grammarAccess.getJdtSourceEditAnswerAccess().getClassNameAssignment_2(), "rule__JdtSourceEditAnswer__ClassNameAssignment_2");
					put(grammarAccess.getJdtSourceEditAnswerAccess().getMethodNamesAssignment_3_1(), "rule__JdtSourceEditAnswer__MethodNamesAssignment_3_1");
					put(grammarAccess.getJdtSourceEditAnswerAccess().getMethodNamesAssignment_3_2_1(), "rule__JdtSourceEditAnswer__MethodNamesAssignment_3_2_1");
					put(grammarAccess.getJdtLaunchAnswerAccess().getClassNameAssignment_2(), "rule__JdtLaunchAnswer__ClassNameAssignment_2");
					put(grammarAccess.getPerspectiveTaskAnswerAccess().getElementIdAssignment_2_0(), "rule__PerspectiveTaskAnswer__ElementIdAssignment_2_0");
					put(grammarAccess.getPerspectiveTaskAnswerAccess().getActionAssignment_2_1_1(), "rule__PerspectiveTaskAnswer__ActionAssignment_2_1_1");
					put(grammarAccess.getPartTaskAnswerAccess().getElementIdAssignment_2_0(), "rule__PartTaskAnswer__ElementIdAssignment_2_0");
					put(grammarAccess.getPartTaskAnswerAccess().getActionAssignment_2_1_1(), "rule__PartTaskAnswer__ActionAssignment_2_1_1");
					put(grammarAccess.getCommandExecutionAnswerAccess().getElementIdAssignment_2_0(), "rule__CommandExecutionAnswer__ElementIdAssignment_2_0");
					put(grammarAccess.getCommandExecutionAnswerAccess().getActionAssignment_2_1_1(), "rule__CommandExecutionAnswer__ActionAssignment_2_1_1");
					put(grammarAccess.getDebugEventAnswerAccess().getElementIdAssignment_2_0(), "rule__DebugEventAnswer__ElementIdAssignment_2_0");
					put(grammarAccess.getDebugEventAnswerAccess().getActionAssignment_2_1_1(), "rule__DebugEventAnswer__ActionAssignment_2_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalXerciseParser typedParser = (InternalXerciseParser) parser;
			typedParser.entryRuleExercise();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public XerciseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XerciseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
