<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="checkstyle" nsURI="platform:/plugin/no.hal.learning.exercise.checkstyle/model/checkstyle-exercise.ecore"
    nsPrefix="checkstyle">
  <eClassifiers xsi:type="ecore:EClass" name="CheckstyleAnswer" eSuperTypes="../../no.hal.learning.exercise.model/model/exercise.ecore#//TaskAnswer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckstyleProposal">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../no.hal.learning.exercise.model/model/exercise.ecore#//TaskProposal">
      <eTypeArguments eClassifier="#//CheckstyleAnswer"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
