/*
* generated by Xtext
*/
package no.hal.emfs.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XemfsStandaloneSetup extends XemfsStandaloneSetupGenerated{

	public static void doSetup() {
		new XemfsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

