<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:exercise="platform:/plugin/no.hal.learning.exercise.model/model/exercise.ecore" xmlns:jdt="platform:/plugin/no.hal.learning.exercise.jdt/model/jdt-exercise.ecore" xmlns:junit="platform:/plugin/no.hal.learning.exercise.junit/model/junit-exercise.ecore" xmlns:workbench="platform:/plugin/no.hal.learning.exercise.workbench/model/workbench-exercise.ecore">
  <exercise:Exercise>
    <parts xsi:type="exercise:ExercisePart" title="Named interface">
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Write source code for the Named interface."/>
        <a xsi:type="jdt:JdtSourceEditAnswer" className="interfaces.Named"/>
      </tasks>
    </parts>
    <parts xsi:type="exercise:ExercisePart" title="Person1 and Person2">
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Write source code for the Person1 class."/>
        <a xsi:type="jdt:JdtSourceEditAnswer" className="interfaces.Person1"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Write source code for the Person2 class."/>
        <a xsi:type="jdt:JdtSourceEditAnswer" className="interfaces.Person2"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Run the Person1Test JUnit test."/>
        <a xsi:type="junit:JunitTestAnswer" testRunName="interfaces.Person1Test"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Run the Person2Test JUnit test."/>
        <a xsi:type="junit:JunitTestAnswer" testRunName="interfaces.Person2Test"/>
      </tasks>
    </parts>
    <parts xsi:type="exercise:ExercisePart" title="NamedComparator">
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Write source code for the NamedComparator class."/>
        <a xsi:type="jdt:JdtSourceEditAnswer" className="interfaces.NamedComparator"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Run the NamedComparatorTest JUnit test."/>
        <a xsi:type="junit:JunitTestAnswer" testRunName="interfaces.NamedComparatorTest"/>
      </tasks>
    </parts>
    <parts xsi:type="exercise:ExercisePart" title="Tool usage">
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use breakpoints to debug code."/>
        <a xsi:type="workbench:DebugEventAnswer" action="suspend.breakpoint"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use the debug command Step Over"/>
        <a xsi:type="workbench:CommandExecutionAnswer" elementId="org.eclipse.debug.ui.commands.StepOver" action="executeSuccess"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use the debug command Step Into"/>
        <a xsi:type="workbench:CommandExecutionAnswer" elementId="org.eclipse.debug.ui.commands.StepInto" action="executeSuccess"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use the Variables view"/>
        <a xsi:type="workbench:PartTaskAnswer" elementId="org.eclipse.debug.ui.VariableView" action="activated"/>
      </tasks>
    </parts>
  </exercise:Exercise>
  <exercise:ExerciseProposals exercise="/0">
    <proposals exercisePart="/0/@parts.0">
      <proposals xsi:type="jdt:JdtSourceEditProposal" question="/0/@parts.0/@tasks.0/@q" answer="/0/@parts.0/@tasks.0/@a"/>
    </proposals>
    <proposals exercisePart="/0/@parts.1">
      <proposals xsi:type="jdt:JdtSourceEditProposal" question="/0/@parts.1/@tasks.0/@q" answer="/0/@parts.1/@tasks.0/@a"/>
      <proposals xsi:type="jdt:JdtSourceEditProposal" question="/0/@parts.1/@tasks.1/@q" answer="/0/@parts.1/@tasks.1/@a">
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457303407222" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="46" warningCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457304220739" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.charAt(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;String LastName = this.fullName.substring(spaceSpot, this.fullName.length());&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="48" warningCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457304445974" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;String LastName = this.fullName.substring(spaceSpot, this.fullName.length());&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="48" warningCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457304459805" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;String LastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="48" warningCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457304492390" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;this.fullName = givenName + &quot; &quot; + lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="49"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457304535199" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;//String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;this.fullName = name + &quot; &quot; + lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;return &#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="50" errorCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457304540172" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;//String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;this.fullName = name + &quot; &quot; + lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;return givenName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="50"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457304548400" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;this.fullName = name + &quot; &quot; + lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;return givenName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="49"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457304607856" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;this.fullName = name + &quot; &quot; + lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;return givenName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;this.fullName = givenName + &quot; &quot; + name;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="50"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457304664925" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;this.fullName = name + &quot; &quot; + lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;return givenName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;this.fullName = givenName + &quot; &quot; + name;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;return lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;this.fullName = givenName + &quot; &quot; + familyName;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;// TODO Auto-generated method stub&#xA;&#x9;&#x9;return null;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="50"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457304675141" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;this.fullName = name + &quot; &quot; + lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;return givenName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;this.fullName = givenName + &quot; &quot; + name;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;return lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;this.fullName = givenName + &quot; &quot; + familyName;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;return this.fullName;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="49"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457362372435" sourceCode="package interfaces;&#xA;&#xA;public class Person2 implements Named{&#xA;&#x9;&#xA;&#x9;private String fullName;&#xA;&#x9;&#xA;&#x9;Person2(String fullName) {&#xA;&#x9;&#x9;this.fullName = fullName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setGivenName(String name) {&#xA;&#x9;&#x9;//Bruker denne fremgangsmåtene i alle metodene under: finner plassen til&#xA;&#x9;&#x9;&#x9;//space (går ut ifra at det er én), finner for-og etternavn ut ifra plasseringen til space&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;this.fullName = name + &quot; &quot; + lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getGivenName() {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;return givenName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFamilyName(String name) {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String givenName = this.fullName.substring(0, spaceSpot);&#xA;&#x9;&#x9;this.fullName = givenName + &quot; &quot; + name;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFamilyName() {&#xA;&#x9;&#x9;int spaceSpot = this.fullName.indexOf(' ');&#xA;&#x9;&#x9;String lastName = this.fullName.substring(spaceSpot+1, this.fullName.length());&#xA;&#x9;&#x9;return lastName;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public void setFullName(String givenName, String familyName) {&#xA;&#x9;&#x9;this.fullName = givenName + &quot; &quot; + familyName;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;&#x9;@Override&#xA;&#x9;public String getFullName() {&#xA;&#x9;&#x9;return this.fullName;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="51"/>
      </proposals>
      <proposals xsi:type="junit:JunitTestProposal" question="/0/@parts.1/@tasks.2/@q" answer="/0/@parts.1/@tasks.2/@a" completion="1.0">
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1457303390598" completion="1.0" successCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1457360777935" completion="1.0" successCount="1"/>
      </proposals>
      <proposals xsi:type="junit:JunitTestProposal" question="/0/@parts.1/@tasks.3/@q" answer="/0/@parts.1/@tasks.3/@a" completion="1.0">
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1457304692569" completion="1.0" successCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1457360824319" completion="1.0" successCount="1"/>
      </proposals>
    </proposals>
    <proposals exercisePart="/0/@parts.2">
      <proposals xsi:type="jdt:JdtSourceEditProposal" question="/0/@parts.2/@tasks.0/@q" answer="/0/@parts.2/@tasks.0/@a">
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349010253" sourceCode="package interfaces;&#xA;&#xA;public class NamedComparator {&#xA;&#xA;}&#xA;" sizeMeasure="5"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349035536" sourceCode="package interfaces;&#xA;&#xA;public class NamedComparator implements Comparator{&#xA;&#xA;}&#xA;" sizeMeasure="5" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349053328" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Object arg0, Object arg1) {&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="12" errorCount="1" warningCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349114476" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Person1 p1, Person2 p2) {&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="12" errorCount="2" warningCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349126218" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator{&#xA;&#xA;&#x9;public int compare(Person1 p1, Person2 p2) {&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="11" errorCount="2" warningCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349144047" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Object p1, Object p2) {&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="12" errorCount="1" warningCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349166671" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Object p1, Object p2) {&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="12" errorCount="3"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349196741" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named p1, Named p2) {&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return 0;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="13"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349310382" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return 0;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="13"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349325256" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return 0;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="13"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349458450" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if((compareTo(named1.getFamilyName(),named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return 0;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="15" errorCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349521308" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="17" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349592369" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="17" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457349602497" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="20"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357013411" sourceCode="package interfaces;&#xA;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="24"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357062429" sourceCode="package interfaces;&#xA;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="26" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357093255" sourceCode="package interfaces;&#xA;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="26" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357119348" sourceCode="package interfaces;&#xA;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="27" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357156265" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList.addAll(p1,p2);&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="29" errorCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357176439" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList.addAll(p1,p2);&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="29" errorCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357187817" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named>.addAll(p1,p2);&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="29" errorCount="6"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357215499" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList();&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="29" errorCount="1" warningCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357218212" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="29" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357229857" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.addAll(p1, p2)&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="30" errorCount="3"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357230900" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.addAll(p1, p2);&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="30" errorCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357248610" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(arg0);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="31" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357301776" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, NamedComparator());&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="31" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357311090" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="31"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357321914" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;System.out.println(Collections.sort(personList, new NamedComparator()));&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="31" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357335154" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;System.out.print(Collections.sort(personList, new NamedComparator()));&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="31" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357340676" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="31"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357358034" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;System.out.println(personList);&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="32"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357370663" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="31"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357728968" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="30"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457357931706" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="30"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359150509" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="30"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359209894" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;System.out.println();&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="31"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359236993" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;,&quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person1 p2 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Person1 )&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="31" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359241355" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person1 p2 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Person1 )&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="31" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359251009" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person1 p2 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Person1 person : personList) {&#xA;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="33" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359273946" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="33" warningCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359288694" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.toString());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="33"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359321347" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="33"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359384435" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p3 = new Person2(&quot;Anna And&quot;);&#xA;&#x9;&#x9;Person2 p4 = new Person2(&quot;Wilhelm Wims&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="35" warningCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359435363" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p3 = new Person2(&quot;Anna And&quot;);&#xA;&#x9;&#x9;Person2 p4 = new Person2(&quot;Wilhelm Wims&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.addAll(p1, p2, p3, p4);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="34" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359466737" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p3 = new Person2(&quot;Anna And&quot;);&#xA;&#x9;&#x9;Person2 p4 = new Person2(&quot;Wilhelm Wims&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="34" warningCount="3"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457359475260" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p3 = new Person2(&quot;Anna And&quot;);&#xA;&#x9;&#x9;Person2 p4 = new Person2(&quot;Wilhelm Wims&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;personList.add(p3);&#xA;&#x9;&#x9;personList.add(p4);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="37"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457360582076" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p3 = new Person2(&quot;Anna And&quot;);&#xA;&#x9;&#x9;Person2 p4 = new Person2(&quot;Wilhelm Wims&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;personList.add(p3);&#xA;&#x9;&#x9;personList.add(p4);&#xA;&#x9;&#x9;personList.addAll((p1,p2,p3,p4).asCollection);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="38" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457360607068" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p3 = new Person2(&quot;Anna And&quot;);&#xA;&#x9;&#x9;Person2 p4 = new Person2(&quot;Wilhelm Wims&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;personList.add(p3);&#xA;&#x9;&#x9;personList.add(p4);&#xA;&#x9;&#x9;personList.addAll((p1,p2,p3,p4).asList);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="38" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457360621275" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p3 = new Person2(&quot;Anna And&quot;);&#xA;&#x9;&#x9;Person2 p4 = new Person2(&quot;Wilhelm Wims&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;personList.add(p3);&#xA;&#x9;&#x9;personList.add(p4);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="37"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457362449738" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;//Hvis etternavn hos named1 (n1) og named2 (n2) er ulike, returner &quot;ulikheten&quot;&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;//Hvis fornavn hos named1 (n1) og named2 (n2) er ulike, returner &quot;ulikheten&quot;&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p3 = new Person2(&quot;Anna And&quot;);&#xA;&#x9;&#x9;Person2 p4 = new Person2(&quot;Wilhelm Wims&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;personList.add(p3);&#xA;&#x9;&#x9;personList.add(p4);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="39"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457362463296" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;//Hvis etternavn hos named1 (n1) og named2 (n2) er ulike, returner &quot;ulikheten&quot;&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;//Hvis fornavn hos named1 (n1) og named2 (n2) er ulike, returner &quot;ulikheten&quot;&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;//Hvis både for- og etternavn er like, returner 0&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p3 = new Person2(&quot;Anna And&quot;);&#xA;&#x9;&#x9;Person2 p4 = new Person2(&quot;Wilhelm Wims&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;personList.add(p3);&#xA;&#x9;&#x9;personList.add(p4);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="40"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1457362478770" sourceCode="package interfaces;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collections;&#xA;import java.util.Comparator;&#xA;&#xA;public class NamedComparator implements Comparator&lt;Named>{&#xA;&#xA;&#x9;@Override&#xA;&#x9;public int compare(Named named1, Named named2) {&#xA;&#x9;&#x9;if(named1.getFamilyName().compareTo(named2.getFamilyName()) != 0) {&#xA;&#x9;&#x9;&#x9;//Hvis etternavn hos named1 (n1) og named2 (n2) er ulike, returner &quot;ulikheten&quot;&#xA;&#x9;&#x9;&#x9;return named1.getFamilyName().compareTo(named2.getFamilyName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else if (named1.getGivenName().compareTo(named2.getGivenName()) != 0){&#xA;&#x9;&#x9;&#x9;//Hvis fornavn hos named1 (n1) og named2 (n2) er ulike, returner &quot;ulikheten&quot;&#xA;&#x9;&#x9;&#x9;return named1.getGivenName().compareTo(named2.getGivenName());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;else {&#xA;&#x9;&#x9;&#x9;//Hvis både for- og etternavn er like, returner 0&#xA;&#x9;&#x9;&#x9;return 0;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;//For testing&#xA;&#x9;&#x9;Person1 p1 = new Person1(&quot;Hans&quot;, &quot;Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p2 = new Person2(&quot;Hans Fredriksen&quot;);&#xA;&#x9;&#x9;Person2 p3 = new Person2(&quot;Anna And&quot;);&#xA;&#x9;&#x9;Person2 p4 = new Person2(&quot;Wilhelm Wims&quot;);&#xA;&#x9;&#x9;ArrayList&lt;Named> personList = new ArrayList&lt;>();&#xA;&#x9;&#x9;personList.add(p1);&#xA;&#x9;&#x9;personList.add(p2);&#xA;&#x9;&#x9;personList.add(p3);&#xA;&#x9;&#x9;personList.add(p4);&#xA;&#x9;&#x9;Collections.sort(personList, new NamedComparator());&#xA;&#x9;&#x9;for (Named person : personList) {&#xA;&#x9;&#x9;&#x9;System.out.println(person.getFullName());&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="41"/>
      </proposals>
      <proposals xsi:type="junit:JunitTestProposal" question="/0/@parts.2/@tasks.1/@q" answer="/0/@parts.2/@tasks.1/@a" completion="1.0">
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1457349617751" completion="1.0" successCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1457360916946" completion="1.0" successCount="2"/>
      </proposals>
    </proposals>
    <proposals exercisePart="/0/@parts.3">
      <proposals xsi:type="workbench:DebugEventProposal" question="/0/@parts.3/@tasks.0/@q" answer="/0/@parts.3/@tasks.0/@a" completion="0.0" performedCount="4">
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
      </proposals>
      <proposals xsi:type="workbench:CommandExecutionProposal" question="/0/@parts.3/@tasks.1/@q" answer="/0/@parts.3/@tasks.1/@a"/>
      <proposals xsi:type="workbench:CommandExecutionProposal" question="/0/@parts.3/@tasks.2/@q" answer="/0/@parts.3/@tasks.2/@a" completion="0.0" performedCount="41">
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
      </proposals>
      <proposals xsi:type="workbench:PartTaskProposal" question="/0/@parts.3/@tasks.3/@q" answer="/0/@parts.3/@tasks.3/@a" completion="0.0" performedCount="4">
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
      </proposals>
    </proposals>
  </exercise:ExerciseProposals>
</xmi:XMI>
