<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:exercise="platform:/plugin/no.hal.learning.exercise.model/model/exercise.ecore" xmlns:jdt="platform:/plugin/no.hal.learning.exercise.jdt/model/jdt-exercise.ecore" xmlns:junit="platform:/plugin/no.hal.learning.exercise.junit/model/junit-exercise.ecore" xmlns:workbench="platform:/plugin/no.hal.learning.exercise.workbench/model/workbench-exercise.ecore">
  <exercise:Exercise>
    <parts xsi:type="exercise:ExercisePart" title="StopWatch and StopWatchManager">
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Write source code for the Partner class."/>
        <a xsi:type="jdt:JdtSourceEditAnswer" className="objectstructures.Partner"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Run the PartnerTest JUnit test."/>
        <a xsi:type="junit:JunitTestAnswer" testRunName="objectstructures.PartnerTest"/>
      </tasks>
    </parts>
    <parts xsi:type="exercise:ExercisePart" title="Tool usage">
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use breakpoints to debug code."/>
        <a xsi:type="workbench:DebugEventAnswer" action="suspend.breakpoint"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use the debug command Step Over"/>
        <a xsi:type="workbench:CommandExecutionAnswer" elementId="org.eclipse.debug.ui.commands.StepOver" action="executeSuccess"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use the debug command Step Into"/>
        <a xsi:type="workbench:CommandExecutionAnswer" elementId="org.eclipse.debug.ui.commands.StepInto" action="executeSuccess"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use the Variables view"/>
        <a xsi:type="workbench:PartTaskAnswer" elementId="org.eclipse.debug.ui.VariableView" action="activated"/>
      </tasks>
    </parts>
  </exercise:Exercise>
  <exercise:ExerciseProposals exercise="/0">
    <proposals exercisePart="/0/@parts.0">
      <proposals xsi:type="jdt:JdtSourceEditProposal" question="/0/@parts.0/@tasks.0/@q" answer="/0/@parts.0/@tasks.0/@a">
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456260963445" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="18"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456261272042" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if (partner != null) {&#xA;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="24"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456261341188" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if (partner != null) {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = null;&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="27"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456261510805" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="24"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456261627382" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner.equals(null)) {&#xA;&#x9;&#x9;&#x9;this.partner = null;&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="27"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456261819725" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner.equals(null)) {&#xA;&#x9;&#x9;&#x9;this.partner = null;&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="34"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456261995049" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner.equals(null)) {&#xA;&#x9;&#x9;&#x9;this.partner = null;&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#x9;&#xA;//&#x9;public static void main(String[] args) {&#xA;//&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;//&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;//&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;//&#x9;&#x9;p1.setPartner(p2);&#xA;//&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;//&#x9;}&#xA;}&#xA;" sizeMeasure="35"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456316336776" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner.equals(null)) {&#xA;&#x9;&#x9;&#x9;this.partner = null;&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;} &#xA;&#x9;&#x9;if(partner.getPartner() != this.partner){&#xA;&#x9;&#x9;&#x9;partner.setPartner(this.partner);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="38"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456399203107" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner.equals(null)) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner;&#xA;&#x9;&#x9;&#x9;this.partner = null;&#xA;&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="44"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456399800955" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;//&#x9;p1.setPartner(null) -> &#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner.equals(null)) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;//&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;//&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;//&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;System.out.println(tempPartner.getPartner());&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="46"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456399816516" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;//&#x9;p1.setPartner(null) -> &#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;//&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;//&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;//&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;System.out.println(tempPartner.getPartner());&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="46"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456399843254" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;//&#x9;p1.setPartner(null) -> &#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;//&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;//&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;//&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;System.out.println(tempPartner.getPartner());&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="45"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456399854210" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;//&#x9;p1.setPartner(null) -> &#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;//&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;//&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;//&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;System.out.println(tempPartner.getPartner());&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="45"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456399882521" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;//&#x9;p1.setPartner(null) -> &#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;//&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;//&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;//&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;System.out.println(tempPartner.getPartner().getName());&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="45"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456399936160" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;//&#x9;p1.setPartner(null) -> &#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;//&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;//&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;//&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;System.out.println(tempPartner.getPartner().getName());&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="45"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456399972499" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;//&#x9;p1.setPartner(null) -> &#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;//&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;//&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;//&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;System.out.println(tempPartner.getName());&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="45"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456400074793" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;//&#x9;p1.setPartner(null) -> &#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;System.out.println(tempPartner.getName());&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="45"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456400082286" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;//&#x9;p1.setPartner(null) -> &#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} else {&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="44"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456400254128" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} else if(this.partner != partner){&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="44"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456400268638" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} else if(this.partner != partner || this.partner == null){&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="44"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456400289849" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} else if(this.partner != partner || this.partner == null){&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="44"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456400318057" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) {&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} else if(this.partner != partner &amp;&amp; this.partner == null){&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="44"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456400609112" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) { //situation 2&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} else if(this.partner != partner &amp;&amp; this.partner == null){&#xA;//&#x9;&#x9;&#x9;situation 1: p1.setPartner(p2)&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;&#x9;} else {&#xA;//&#x9;&#x9;&#x9;situation 3: p1.setPartner(p4)&#xA;&#x9;&#x9;&#x9;this.setPartner(null); //p1 p2 brudd&#xA;&#x9;&#x9;&#x9;partner.setPartner(null); //p3 p4 brudd&#xA;&#x9;&#x9;&#x9;this.setPartner(partner);&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="50"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1456426733172" sourceCode="package objectstructures;&#xA;&#xA;public class Partner {&#xA;&#x9;private String name;&#xA;&#x9;private Partner partner;&#xA;&#x9;&#xA;&#x9;public Partner(String name) {&#xA;&#x9;&#x9;this.name = name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String getName() {&#xA;&#x9;&#x9;return name;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public Partner getPartner() {&#xA;&#x9;&#x9;return partner;&#xA;&#x9;}&#xA;&#xA;&#x9;public void setPartner(Partner partner) {&#xA;&#x9;&#x9;if(partner == null) { //situation 2&#xA;&#x9;&#x9;&#x9;Partner tempPartner = new Partner(&quot;tempPartner&quot;);&#xA;&#x9;&#x9;&#x9;tempPartner = this.partner; //tempPartner is p2&#xA;&#x9;&#x9;&#x9;this.partner = null; //set partner to p1 = null&#xA;&#x9;&#x9;&#x9;if(tempPartner.getPartner() != null){&#xA;&#x9;&#x9;&#x9;&#x9;tempPartner.setPartner(null);&#x9;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;} else if(this.partner != partner &amp;&amp; this.partner == null){&#xA;//&#x9;&#x9;&#x9;situation 1: p1.setPartner(p2)&#xA;&#x9;&#x9;&#x9;this.partner = partner;&#xA;&#x9;&#x9;&#x9;if(partner.getPartner() != this){&#xA;&#x9;&#x9;&#x9;&#x9;partner.setPartner(this);&#xA;&#x9;&#x9;&#x9;} // this refererer til &quot;dette&quot; objektet&#xA;&#x9;&#x9;} else {&#xA;//&#x9;&#x9;&#x9;situation 3: p1.setPartner(p4)&#xA;&#x9;&#x9;&#x9;this.setPartner(null); //p1 p2 brudd&#xA;&#x9;&#x9;&#x9;partner.setPartner(null); //p3 p4 brudd&#xA;&#x9;&#x9;&#x9;this.setPartner(partner);&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public static void main(String[] args) {&#xA;&#x9;&#x9;Partner p1 = new Partner(&quot;p1&quot;);&#xA;&#x9;&#x9;System.out.println(&quot;Name:&quot; + p1.getName());&#xA;&#x9;&#x9;Partner p2 = new Partner(&quot;p2&quot;);&#xA;&#x9;&#x9;p1.setPartner(p2);&#xA;&#x9;&#x9;System.out.println(&quot;Partner:&quot; + p1.getPartner());&#xA;&#x9;&#x9;p1.setPartner(null);&#xA;&#x9;&#x9;System.out.println(&quot;Brytes:&quot; + p1.getPartner() + p2.getPartner());&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="50"/>
      </proposals>
      <proposals xsi:type="junit:JunitTestProposal" question="/0/@parts.0/@tasks.1/@q" answer="/0/@parts.0/@tasks.1/@a" completion="0.9090909090909091">
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456260989933" completion="1.0" successCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456261343782" completion="0.5" successCount="1" failureCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456261511157" completion="0.3333333333333333" successCount="1" failureCount="2"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456261528364" completion="0.25" successCount="1" failureCount="3"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456261627695" completion="0.2" successCount="1" failureCount="4"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456261885179" completion="0.3333333333333333" successCount="2" failureCount="4"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456399203475" completion="0.0" errorCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456400075099" completion="0.5" successCount="1" errorCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456400085790" completion="0.6666666666666666" successCount="2" errorCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456400087459" completion="0.75" successCount="3" errorCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456400254442" completion="0.8" successCount="4" errorCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456400256678" completion="0.8333333333333334" successCount="5" errorCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456400269034" completion="0.8571428571428571" successCount="6" errorCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456400270172" completion="0.875" successCount="7" errorCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456400318404" completion="0.8888888888888888" successCount="8" errorCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456400319433" completion="0.9" successCount="9" errorCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1456400611143" completion="0.9090909090909091" successCount="10" errorCount="1"/>
      </proposals>
    </proposals>
    <proposals exercisePart="/0/@parts.1">
      <proposals xsi:type="workbench:DebugEventProposal" question="/0/@parts.1/@tasks.0/@q" answer="/0/@parts.1/@tasks.0/@a" completion="0.0" performedCount="3">
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
      </proposals>
      <proposals xsi:type="workbench:CommandExecutionProposal" question="/0/@parts.1/@tasks.1/@q" answer="/0/@parts.1/@tasks.1/@a" completion="0.0" performedCount="9">
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
      </proposals>
      <proposals xsi:type="workbench:CommandExecutionProposal" question="/0/@parts.1/@tasks.2/@q" answer="/0/@parts.1/@tasks.2/@a" completion="0.0" performedCount="4">
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
      </proposals>
      <proposals xsi:type="workbench:PartTaskProposal" question="/0/@parts.1/@tasks.3/@q" answer="/0/@parts.1/@tasks.3/@a" completion="0.0" performedCount="2">
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
      </proposals>
    </proposals>
  </exercise:ExerciseProposals>
</xmi:XMI>
