<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:exercise="platform:/plugin/no.hal.learning.exercise.model/model/exercise.ecore" xmlns:jdt="platform:/plugin/no.hal.learning.exercise.jdt/model/jdt-exercise.ecore" xmlns:junit="platform:/plugin/no.hal.learning.exercise.junit/model/junit-exercise.ecore" xmlns:workbench="platform:/plugin/no.hal.learning.exercise.workbench/model/workbench-exercise.ecore">
  <exercise:Exercise>
    <parts xsi:type="exercise:ExercisePart" title="Train">
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Write source code for the TrainCar superclass."/>
        <a xsi:type="jdt:JdtSourceEditAnswer" className="inheritance.TrainCar"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Write the source code for the CargoCar class."/>
        <a xsi:type="jdt:JdtSourceEditAnswer" className="inheritance.CargoCar"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Write the source code for the PassengerCar class."/>
        <a xsi:type="jdt:JdtSourceEditAnswer" className="inheritance.PassengerCar"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Write the source code for the Train class."/>
        <a xsi:type="jdt:JdtSourceEditAnswer" className="inheritance.Train"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Run the TrainCarTest JUnit test."/>
        <a xsi:type="junit:JunitTestAnswer" testRunName="inheritance.TrainCarTest"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Run the TrainTest JUnit test."/>
        <a xsi:type="junit:JunitTestAnswer" testRunName="inheritance.TrainTest"/>
      </tasks>
    </parts>
    <parts xsi:type="exercise:ExercisePart" title="Tool usage">
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use breakpoints to debug code."/>
        <a xsi:type="workbench:DebugEventAnswer" action="suspend.breakpoint"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use the debug command Step Over"/>
        <a xsi:type="workbench:CommandExecutionAnswer" elementId="org.eclipse.debug.ui.commands.StepOver" action="executeSuccess"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use the debug command Step Into"/>
        <a xsi:type="workbench:CommandExecutionAnswer" elementId="org.eclipse.debug.ui.commands.StepInto" action="executeSuccess"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Use the Variables view"/>
        <a xsi:type="workbench:PartTaskAnswer" elementId="org.eclipse.debug.ui.VariableView" action="activated"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Run the TrainCar class."/>
        <a xsi:type="jdt:JdtLaunchAnswer" className="inheritance.TrainCar"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Run the CargoCar class."/>
        <a xsi:type="jdt:JdtLaunchAnswer" className="inheritance.CargoCar"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Run the PassengerCar class."/>
        <a xsi:type="jdt:JdtLaunchAnswer" className="inheritance.PassengerCar"/>
      </tasks>
      <tasks xsi:type="exercise:Task">
        <q xsi:type="exercise:StringQuestion" question="Run the Train class."/>
        <a xsi:type="jdt:JdtLaunchAnswer" className="inheritance.Train"/>
      </tasks>
    </parts>
  </exercise:Exercise>
  <exercise:ExerciseProposals exercise="/0">
    <proposals exercisePart="/0/@parts.0">
      <proposals xsi:type="jdt:JdtSourceEditProposal" question="/0/@parts.0/@tasks.0/@q" answer="/0/@parts.0/@tasks.0/@a">
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459845996800" sourceCode="package inheritance;&#xA;&#xA;public class TrainCar {&#xA;&#xA;&#x9;private int totalWeight;&#xA;&#x9;private int deadWeight;&#xA;&#x9;&#xA;&#x9;public TrainCar(int deadWeight){&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight() {&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;protected void setDeadWeight(int deadWeight) {&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getDeadWeight() {&#xA;&#x9;&#x9;return deadWeight;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="23"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459847210735" sourceCode="package inheritance;&#xA;&#xA;public class TrainCar {&#xA;&#xA;&#x9;private int totalWeight;&#xA;&#x9;private int deadWeight;&#xA;&#x9;&#xA;&#x9;public TrainCar(int deadWeight){&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight() {&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;protected void setDeadWeight(int deadWeight) {&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getDeadWeight() {&#xA;&#x9;&#x9;return deadWeight;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="23"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459847417160" sourceCode="package inheritance;&#xA;&#xA;public class TrainCar {&#xA;&#xA;&#x9;private int totalWeight;&#xA;&#x9;private int deadWeight;&#xA;&#x9;&#xA;&#x9;public TrainCar(int deadWeight){&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight() {&#xA;&#x9;&#x9;totalWeight = deadWeight;&#xA;&#x9;&#x9;if(this instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;totalWeight += ((CargoCar) this).getCargoWeight();&#xA;&#x9;&#x9;} else if(this instanceof PassengerCar){&#xA;&#x9;&#x9;&#x9;totalWeight += ((PassengerCar) this).getPassengerCount() * 80;&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;protected void setDeadWeight(int deadWeight) {&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getDeadWeight() {&#xA;&#x9;&#x9;return deadWeight;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="29"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459938161020" sourceCode="package inheritance;&#xA;&#xA;public class TrainCar {&#xA;&#xA;&#x9;protected int totalWeight;&#xA;&#x9;private int deadWeight;&#xA;&#x9;&#xA;&#x9;public TrainCar(int deadWeight){&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;//&#x9;public int getTotalWeight() {&#xA;//&#x9;&#x9;totalWeight = deadWeight;&#xA;//&#x9;&#x9;if(this instanceof CargoCar){&#xA;//&#x9;&#x9;&#x9;totalWeight += ((CargoCar) this).getCargoWeight();&#xA;//&#x9;&#x9;} else if(this instanceof PassengerCar){&#xA;//&#x9;&#x9;&#x9;totalWeight += ((PassengerCar) this).getPassengerCount() * 80;&#xA;//&#x9;&#x9;}&#xA;//&#x9;&#x9;return totalWeight;&#xA;//&#x9;}&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;totalWeight = deadWeight;&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;protected void setDeadWeight(int deadWeight) {&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getDeadWeight() {&#xA;&#x9;&#x9;return deadWeight;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="33"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459938778565" sourceCode="package inheritance;&#xA;&#xA;public class TrainCar {&#xA;&#xA;&#x9;protected int totalWeight;&#xA;&#x9;private int deadWeight;&#xA;&#x9;&#xA;&#x9;public TrainCar(int deadWeight){&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;&#x9;totalWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;//&#x9;public int getTotalWeight() {&#xA;//&#x9;&#x9;totalWeight = deadWeight;&#xA;//&#x9;&#x9;if(this instanceof CargoCar){&#xA;//&#x9;&#x9;&#x9;totalWeight += ((CargoCar) this).getCargoWeight();&#xA;//&#x9;&#x9;} else if(this instanceof PassengerCar){&#xA;//&#x9;&#x9;&#x9;totalWeight += ((PassengerCar) this).getPassengerCount() * 80;&#xA;//&#x9;&#x9;}&#xA;//&#x9;&#x9;return totalWeight;&#xA;//&#x9;}&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;protected void setDeadWeight(int deadWeight) {&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getDeadWeight() {&#xA;&#x9;&#x9;return deadWeight;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="33"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459938988772" sourceCode="package inheritance;&#xA;&#xA;public class TrainCar {&#xA;&#xA;&#x9;protected int totalWeight;&#xA;&#x9;private int deadWeight;&#xA;&#x9;&#xA;&#x9;public TrainCar(int deadWeight){&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;&#x9;totalWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;//&#x9;public int getTotalWeight() { instead of this, use method &quot;redefine&quot;&#xA;//&#x9;&#x9;totalWeight = deadWeight;&#xA;//&#x9;&#x9;if(this instanceof CargoCar){&#xA;//&#x9;&#x9;&#x9;totalWeight += ((CargoCar) this).getCargoWeight();&#xA;//&#x9;&#x9;} else if(this instanceof PassengerCar){&#xA;//&#x9;&#x9;&#x9;totalWeight += ((PassengerCar) this).getPassengerCount() * 80;&#xA;//&#x9;&#x9;}&#xA;//&#x9;&#x9;return totalWeight;&#xA;//&#x9;}&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;protected void setDeadWeight(int deadWeight) {&#xA;&#x9;&#x9;this.deadWeight = deadWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getDeadWeight() {&#xA;&#x9;&#x9;return deadWeight;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="33"/>
      </proposals>
      <proposals xsi:type="jdt:JdtSourceEditProposal" question="/0/@parts.0/@tasks.1/@q" answer="/0/@parts.0/@tasks.1/@a">
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459845988665" sourceCode="package inheritance;&#xA;&#xA;public class CargoCar extends TrainCar{&#xA;&#xA;&#x9;private int cargoWeight;&#xA;&#x9;&#xA;&#x9;public CargoCar(int deadWeight, int cargoWeight) {&#xA;&#x9;&#x9;super(deadWeight);&#xA;&#x9;&#x9;this.cargoWeight = cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight() {&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setCargoWeight(int cargoWeight) {&#xA;&#x9;&#x9;this.cargoWeight = cargoWeight;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="20"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459845990026" sourceCode="package inheritance;&#xA;&#xA;public class CargoCar extends TrainCar{&#xA;&#xA;&#x9;private int cargoWeight;&#xA;&#x9;&#xA;&#x9;public CargoCar(int deadWeight, int cargoWeight) {&#xA;&#x9;&#x9;super(deadWeight);&#xA;&#x9;&#x9;this.cargoWeight = cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight() {&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setCargoWeight(int cargoWeight) {&#xA;&#x9;&#x9;this.cargoWeight = cargoWeight;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="20"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459938836440" sourceCode="package inheritance;&#xA;&#xA;public class CargoCar extends TrainCar{&#xA;&#xA;&#x9;private int cargoWeight;&#xA;&#x9;&#xA;&#x9;public CargoCar(int deadWeight, int cargoWeight) {&#xA;&#x9;&#x9;super(deadWeight);&#xA;&#x9;&#x9;this.cargoWeight = cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight() {&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setCargoWeight(int cargoWeight) {&#xA;&#x9;&#x9;this.cargoWeight = cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;@Override&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;return super.getTotalWeight() + getCargoWeight();&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="25"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459938985680" sourceCode="package inheritance;&#xA;&#xA;public class CargoCar extends TrainCar{&#xA;&#xA;&#x9;private int cargoWeight;&#xA;&#x9;&#xA;&#x9;public CargoCar(int deadWeight, int cargoWeight) {&#xA;&#x9;&#x9;super(deadWeight);&#xA;&#x9;&#x9;this.cargoWeight = cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight() {&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setCargoWeight(int cargoWeight) {&#xA;&#x9;&#x9;this.cargoWeight = cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;@Override&#xA;&#x9;public int getTotalWeight(){ //redefine&#xA;&#x9;&#x9;return super.getTotalWeight() + getCargoWeight();&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="25"/>
      </proposals>
      <proposals xsi:type="jdt:JdtSourceEditProposal" question="/0/@parts.0/@tasks.2/@q" answer="/0/@parts.0/@tasks.2/@a">
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459846003438" sourceCode="package inheritance;&#xA;&#xA;public class PassengerCar extends TrainCar{&#xA;&#xA;&#x9;private int passengerCount;&#xA;&#xA;&#x9;public PassengerCar(int deadWeight, int passengerCount) {&#xA;&#x9;&#x9;super(deadWeight);&#xA;&#x9;&#x9;this.passengerCount = passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount() {&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPassengerCount(int passengerCount) {&#xA;&#x9;&#x9;this.passengerCount = passengerCount;&#xA;&#x9;}&#xA;&#xA;}&#xA;" sizeMeasure="20"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459846006882" sourceCode="package inheritance;&#xA;&#xA;public class PassengerCar extends TrainCar{&#xA;&#xA;&#x9;private int passengerCount;&#xA;&#xA;&#x9;public PassengerCar(int deadWeight, int passengerCount) {&#xA;&#x9;&#x9;super(deadWeight);&#xA;&#x9;&#x9;this.passengerCount = passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount() {&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPassengerCount(int passengerCount) {&#xA;&#x9;&#x9;this.passengerCount = passengerCount;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="19"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459938929910" sourceCode="package inheritance;&#xA;&#xA;public class PassengerCar extends TrainCar{&#xA;&#xA;&#x9;private int passengerCount;&#xA;&#xA;&#x9;public PassengerCar(int deadWeight, int passengerCount) {&#xA;&#x9;&#x9;super(deadWeight);&#xA;&#x9;&#x9;this.passengerCount = passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount() {&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public void setPassengerCount(int passengerCount) {&#xA;&#x9;&#x9;this.passengerCount = passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;@Override&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;return super.getTotalWeight() + getPassengerCount()* 80;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="24"/>
      </proposals>
      <proposals xsi:type="jdt:JdtSourceEditProposal" question="/0/@parts.0/@tasks.3/@q" answer="/0/@parts.0/@tasks.3/@a">
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459846458239" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="20" errorCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459846836647" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;private int passengerCount;&#xA;&#x9;private int cargoWeight;&#xA;&#x9;&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;int totalWeight = 0;&#xA;&#x9;&#x9;for(TrainCar trainCar : carList){&#xA;&#x9;&#x9;&#x9;totalWeight += trainCar.getDeadWeight();&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;totalWeight += getPassengerCount()*80 + getCargoWeight();&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount(){&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight(){&#xA;&#x9;&#x9;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="36" errorCount="2" warningCount="2"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459847025356" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;private int passengerCount=0;&#xA;&#x9;private int cargoWeight=0;&#xA;&#x9;&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;int totalWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;totalWeight += car.getDeadWeight();&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;totalWeight += getPassengerCount()*80 + getCargoWeight();&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof PassengerCar){&#xA;&#x9;&#x9;&#x9;&#x9;passengerCount += ((PassengerCar) car).getPassengerCount();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;cargoWeight += ((CargoCar) car).getCargoWeight();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="46"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459847423340" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;private int passengerCount=0;&#xA;&#x9;private int cargoWeight=0;&#xA;&#x9;&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;int totalWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;totalWeight += car.getDeadWeight();&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;totalWeight += getPassengerCount()*80 + getCargoWeight();&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof PassengerCar){&#xA;&#x9;&#x9;&#x9;&#x9;passengerCount += ((PassengerCar) car).getPassengerCount();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;cargoWeight += ((CargoCar) car).getCargoWeight();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String toString(){&#xA;&#x9;&#x9;String print = &quot;&quot;;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return print;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="54" warningCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459847476872" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;private int passengerCount=0;&#xA;&#x9;private int cargoWeight=0;&#xA;&#x9;&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;int totalWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;//&#x9;&#x9;&#x9;totalWeight += car.getDeadWeight();&#xA;&#x9;&#x9;&#x9;totalWeight += car.getTotalWeight();&#xA;&#x9;&#x9;}&#xA;//&#x9;&#x9;totalWeight += getPassengerCount()*80 + getCargoWeight();&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof PassengerCar){&#xA;&#x9;&#x9;&#x9;&#x9;passengerCount += ((PassengerCar) car).getPassengerCount();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;cargoWeight += ((CargoCar) car).getCargoWeight();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String toString(){&#xA;&#x9;&#x9;String print = &quot;&quot;;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return print;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="55" warningCount="1"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459848113000" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;private int passengerCount=0;&#xA;&#x9;private int cargoWeight=0;&#xA;&#x9;&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;int totalWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;//&#x9;&#x9;&#x9;totalWeight += car.getDeadWeight();&#xA;&#x9;&#x9;&#x9;totalWeight += car.getTotalWeight();&#xA;&#x9;&#x9;}&#xA;//&#x9;&#x9;totalWeight += getPassengerCount()*80 + getCargoWeight();&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof PassengerCar){&#xA;&#x9;&#x9;&#x9;&#x9;passengerCount += ((PassengerCar) car).getPassengerCount();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;cargoWeight += ((CargoCar) car).getCargoWeight();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String toString(){&#xA;&#x9;&#x9;String print = &quot;&quot;;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Cargo weight: &quot; + ((CargoCar) car).getCargoWeight();&#xA;&#x9;&#x9;&#x9;} else{&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Total passenger: &quot; + ((PassengerCar) car).getPassengerCount();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return print;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="59"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459848138519" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;private int passengerCount=0;&#xA;&#x9;private int cargoWeight=0;&#xA;&#x9;&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;int totalWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;//&#x9;&#x9;&#x9;totalWeight += car.getDeadWeight();&#xA;&#x9;&#x9;&#x9;totalWeight += car.getTotalWeight();&#xA;&#x9;&#x9;}&#xA;//&#x9;&#x9;totalWeight += getPassengerCount()*80 + getCargoWeight();&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof PassengerCar){&#xA;&#x9;&#x9;&#x9;&#x9;passengerCount += ((PassengerCar) car).getPassengerCount();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;cargoWeight += ((CargoCar) car).getCargoWeight();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String toString(){&#xA;&#x9;&#x9;String print = &quot;&quot;;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Cargo weight: &quot; + ((CargoCar) car).getCargoWeight() + &quot;\n&quot;;&#xA;&#x9;&#x9;&#x9;} else{&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Total passenger: &quot; + ((PassengerCar) car).getPassengerCount() + &quot;\n&quot;;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return print;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="59"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459848898144" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;private int passengerCount;&#xA;&#x9;private int cargoWeight;&#xA;&#x9;&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;int totalWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;//&#x9;&#x9;&#x9;totalWeight += car.getDeadWeight();&#xA;&#x9;&#x9;&#x9;totalWeight += car.getTotalWeight();&#xA;&#x9;&#x9;}&#xA;//&#x9;&#x9;totalWeight += getPassengerCount()*80 + getCargoWeight();&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof PassengerCar){&#xA;&#x9;&#x9;&#x9;&#x9;passengerCount += ((PassengerCar) car).getPassengerCount();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight(){&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;cargoWeight += ((CargoCar) car).getCargoWeight();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String toString(){&#xA;&#x9;&#x9;String print = &quot;&quot;;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Cargo weight: &quot; + ((CargoCar) car).getCargoWeight() + &quot;\n&quot;;&#xA;&#x9;&#x9;&#x9;} else{&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Total passenger: &quot; + ((PassengerCar) car).getPassengerCount() + &quot;\n&quot;;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return print;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="59"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459848922741" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;private int passengerCount;&#xA;&#x9;private int cargoWeight;&#xA;&#x9;&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;int totalWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;//&#x9;&#x9;&#x9;totalWeight += car.getDeadWeight();&#xA;&#x9;&#x9;&#x9;totalWeight += car.getTotalWeight();&#xA;&#x9;&#x9;}&#xA;//&#x9;&#x9;totalWeight += getPassengerCount()*80 + getCargoWeight();&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount(){&#xA;&#x9;&#x9;passengerCount = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof PassengerCar){&#xA;&#x9;&#x9;&#x9;&#x9;passengerCount += ((PassengerCar) car).getPassengerCount();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight(){&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;cargoWeight += ((CargoCar) car).getCargoWeight();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String toString(){&#xA;&#x9;&#x9;String print = &quot;&quot;;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Cargo weight: &quot; + ((CargoCar) car).getCargoWeight() + &quot;\n&quot;;&#xA;&#x9;&#x9;&#x9;} else{&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Total passenger: &quot; + ((PassengerCar) car).getPassengerCount() + &quot;\n&quot;;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return print;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="61"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459848931794" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;private int passengerCount;&#xA;&#x9;private int cargoWeight;&#xA;&#x9;&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;int totalWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;//&#x9;&#x9;&#x9;totalWeight += car.getDeadWeight();&#xA;&#x9;&#x9;&#x9;totalWeight += car.getTotalWeight();&#xA;&#x9;&#x9;}&#xA;//&#x9;&#x9;totalWeight += getPassengerCount()*80 + getCargoWeight();&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount(){&#xA;&#x9;&#x9;passengerCount = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof PassengerCar){&#xA;&#x9;&#x9;&#x9;&#x9;passengerCount += ((PassengerCar) car).getPassengerCount();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight(){&#xA;&#x9;&#x9;cargoWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;cargoWeight += ((CargoCar) car).getCargoWeight();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String toString(){&#xA;&#x9;&#x9;String print = &quot;&quot;;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Cargo weight: &quot; + ((CargoCar) car).getCargoWeight() + &quot;\n&quot;;&#xA;&#x9;&#x9;&#x9;} else{&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Total passenger: &quot; + ((PassengerCar) car).getPassengerCount() + &quot;\n&quot;;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return print;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="61"/>
        <attempts xsi:type="jdt:JdtSourceEditEvent" timestamp="1459848958053" sourceCode="package inheritance;&#xA;&#xA;import java.util.ArrayList;&#xA;import java.util.Collection;&#xA;&#xA;public class Train {&#xA;&#xA;&#x9;Collection&lt;TrainCar> carList = new ArrayList&lt;TrainCar>();&#xA;&#x9;private int passengerCount;&#xA;&#x9;private int cargoWeight;&#xA;&#x9;&#xA;&#x9;public void addTrainCar(TrainCar car){&#xA;&#x9;&#x9;carList.add(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public boolean contains(TrainCar car){&#xA;&#x9;&#x9;return carList.contains(car);&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getTotalWeight(){&#xA;&#x9;&#x9;int totalWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;totalWeight += car.getTotalWeight();&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return totalWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getPassengerCount(){&#xA;&#x9;&#x9;passengerCount = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof PassengerCar){&#xA;&#x9;&#x9;&#x9;&#x9;passengerCount += ((PassengerCar) car).getPassengerCount();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return passengerCount;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public int getCargoWeight(){&#xA;&#x9;&#x9;cargoWeight = 0;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;cargoWeight += ((CargoCar) car).getCargoWeight();&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return cargoWeight;&#xA;&#x9;}&#xA;&#x9;&#xA;&#x9;public String toString(){&#xA;&#x9;&#x9;String print = &quot;&quot;;&#xA;&#x9;&#x9;for(TrainCar car : carList){&#xA;&#x9;&#x9;&#x9;if(car instanceof CargoCar){&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Cargo weight: &quot; + ((CargoCar) car).getCargoWeight() + &quot;\n&quot;;&#xA;&#x9;&#x9;&#x9;} else{&#xA;&#x9;&#x9;&#x9;&#x9;print += &quot;[&quot; + car + &quot;: &quot; + &quot;Cargo Car. Total weight: &quot; + car.getTotalWeight() + &quot;Total passenger: &quot; + ((PassengerCar) car).getPassengerCount() + &quot;\n&quot;;&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return print;&#xA;&#x9;}&#xA;}&#xA;" sizeMeasure="59"/>
      </proposals>
      <proposals xsi:type="junit:JunitTestProposal" question="/0/@parts.0/@tasks.4/@q" answer="/0/@parts.0/@tasks.4/@a" completion="1.0">
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459848352893" completion="1.0" successCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459938779007" completion="1.0" successCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459940449517" completion="1.0" successCount="2"/>
      </proposals>
      <proposals xsi:type="junit:JunitTestProposal" question="/0/@parts.0/@tasks.5/@q" answer="/0/@parts.0/@tasks.5/@a" completion="0.875">
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459848359539" completion="1.0" successCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459848360867" completion="1.0" successCount="2"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459848362160" completion="0.6666666666666666" successCount="2" failureCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459848363373" completion="0.5" successCount="2" failureCount="2"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459848898557" completion="0.4" successCount="2" failureCount="3"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459848923007" completion="0.5" successCount="3" failureCount="3"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459848935317" completion="0.5714285714285714" successCount="4" failureCount="3"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459938865054" completion="0.75" successCount="3" failureCount="1"/>
        <attempts xsi:type="junit:JunitTestEvent" timestamp="1459938930248" completion="0.875" successCount="7" failureCount="1"/>
      </proposals>
    </proposals>
    <proposals exercisePart="/0/@parts.1">
      <proposals xsi:type="workbench:DebugEventProposal" question="/0/@parts.1/@tasks.0/@q" answer="/0/@parts.1/@tasks.0/@a" completion="0.0" performedCount="3">
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
      </proposals>
      <proposals xsi:type="workbench:CommandExecutionProposal" question="/0/@parts.1/@tasks.1/@q" answer="/0/@parts.1/@tasks.1/@a" completion="0.0" performedCount="29">
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
        <attempts timestamp="-1" completion="0.0"/>
      </proposals>
      <proposals xsi:type="workbench:CommandExecutionProposal" question="/0/@parts.1/@tasks.2/@q" answer="/0/@parts.1/@tasks.2/@a"/>
      <proposals xsi:type="workbench:PartTaskProposal" question="/0/@parts.1/@tasks.3/@q" answer="/0/@parts.1/@tasks.3/@a" completion="0.0" performedCount="1">
        <attempts timestamp="-1" completion="0.0"/>
      </proposals>
      <proposals xsi:type="jdt:JdtLaunchProposal" question="/0/@parts.1/@tasks.4/@q" answer="/0/@parts.1/@tasks.4/@a"/>
      <proposals xsi:type="jdt:JdtLaunchProposal" question="/0/@parts.1/@tasks.5/@q" answer="/0/@parts.1/@tasks.5/@a"/>
      <proposals xsi:type="jdt:JdtLaunchProposal" question="/0/@parts.1/@tasks.6/@q" answer="/0/@parts.1/@tasks.6/@a"/>
      <proposals xsi:type="jdt:JdtLaunchProposal" question="/0/@parts.1/@tasks.7/@q" answer="/0/@parts.1/@tasks.7/@a"/>
    </proposals>
  </exercise:ExerciseProposals>
</xmi:XMI>
