/**
 * generated by Xtext 2.9.1
 */
package no.hal.learning.exercise.xtext.validation;

import no.hal.learning.exercise.xtext.validation.AbstractXerciseValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class XerciseValidator extends AbstractXerciseValidator {
}
