/*
* generated by Xtext
*/
package no.hal.jex.jextest.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import no.hal.jex.jextest.services.JexTestGrammarAccess;

public class JexTestParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private JexTestGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected no.hal.jex.jextest.parser.antlr.internal.InternalJexTestParser createParser(XtextTokenStream stream) {
		return new no.hal.jex.jextest.parser.antlr.internal.InternalJexTestParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "JexTestSuite";
	}
	
	public JexTestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JexTestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
