/*
 * generated by Xtext
 */
package no.hal.jex.jextest.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JexTestAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("no/hal/jex/jextest/parser/antlr/internal/InternalJexTest.tokens");
	}
}
