/**
 * generated by Xtext 2.9.1
 */
package no.hal.learning.exercise.xtext.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class XerciseDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
