/*
* generated by Xtext
*/
package no.hal.jex.jextest.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.xbase.services.XbaseGrammarAccess;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;

@Singleton
public class JexTestGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class JexTestCaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JexTestCase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTestKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTestedClassAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTestedClassJvmParameterizedTypeReferenceParserRuleCall_1_0 = (RuleCall)cTestedClassAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cWithKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTestClassNameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTestClassNameQNameParserRuleCall_2_1_0 = (RuleCall)cTestClassNameAssignment_2_1.eContents().get(0);
		private final Assignment cDescriptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_3_0 = (RuleCall)cDescriptionAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommercialAtKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUrlAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUrlSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cUrlAssignment_4_1.eContents().get(0);
		private final Assignment cImportSectionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cImportSectionXImportSectionParserRuleCall_5_0 = (RuleCall)cImportSectionAssignment_5.eContents().get(0);
		private final Alternatives cAlternatives_6 = (Alternatives)cGroup.eContents().get(6);
		private final Group cGroup_6_0 = (Group)cAlternatives_6.eContents().get(0);
		private final Alternatives cAlternatives_6_0_0 = (Alternatives)cGroup_6_0.eContents().get(0);
		private final Keyword cInstanceKeyword_6_0_0_0 = (Keyword)cAlternatives_6_0_0.eContents().get(0);
		private final Keyword cValKeyword_6_0_0_1 = (Keyword)cAlternatives_6_0_0.eContents().get(1);
		private final Assignment cInstancesAssignment_6_0_1 = (Assignment)cGroup_6_0.eContents().get(1);
		private final RuleCall cInstancesInstanceParserRuleCall_6_0_1_0 = (RuleCall)cInstancesAssignment_6_0_1.eContents().get(0);
		private final Group cGroup_6_0_2 = (Group)cGroup_6_0.eContents().get(2);
		private final Keyword cCommaKeyword_6_0_2_0 = (Keyword)cGroup_6_0_2.eContents().get(0);
		private final Assignment cInstancesAssignment_6_0_2_1 = (Assignment)cGroup_6_0_2.eContents().get(1);
		private final RuleCall cInstancesInstanceParserRuleCall_6_0_2_1_0 = (RuleCall)cInstancesAssignment_6_0_2_1.eContents().get(0);
		private final Assignment cStateFunctionsAssignment_6_1 = (Assignment)cAlternatives_6.eContents().get(1);
		private final RuleCall cStateFunctionsStateFunctionParserRuleCall_6_1_0 = (RuleCall)cStateFunctionsAssignment_6_1.eContents().get(0);
		private final Assignment cTestSequencesAssignment_6_2 = (Assignment)cAlternatives_6.eContents().get(2);
		private final RuleCall cTestSequencesJexTestSequenceParserRuleCall_6_2_0 = (RuleCall)cTestSequencesAssignment_6_2.eContents().get(0);
		private final Assignment cMethodsAssignment_6_3 = (Assignment)cAlternatives_6.eContents().get(3);
		private final RuleCall cMethodsMethodParserRuleCall_6_3_0 = (RuleCall)cMethodsAssignment_6_3.eContents().get(0);
		
		//JexTestCase:
		//	"test" testedClass=JvmParameterizedTypeReference ("with" testClassName=QName)? description=STRING? ("@" url=STRING)?
		//	importSection=XImportSection? (("instance" | "val") instances+=Instance ("," instances+=Instance)* |
		//	stateFunctions+=StateFunction | testSequences+=JexTestSequence | methods+=Method)*;
		public ParserRule getRule() { return rule; }

		//"test" testedClass=JvmParameterizedTypeReference ("with" testClassName=QName)? description=STRING? ("@" url=STRING)?
		//importSection=XImportSection? (("instance" | "val") instances+=Instance ("," instances+=Instance)* |
		//stateFunctions+=StateFunction | testSequences+=JexTestSequence | methods+=Method)*
		public Group getGroup() { return cGroup; }

		//"test"
		public Keyword getTestKeyword_0() { return cTestKeyword_0; }

		//testedClass=JvmParameterizedTypeReference
		public Assignment getTestedClassAssignment_1() { return cTestedClassAssignment_1; }

		//JvmParameterizedTypeReference
		public RuleCall getTestedClassJvmParameterizedTypeReferenceParserRuleCall_1_0() { return cTestedClassJvmParameterizedTypeReferenceParserRuleCall_1_0; }

		//("with" testClassName=QName)?
		public Group getGroup_2() { return cGroup_2; }

		//"with"
		public Keyword getWithKeyword_2_0() { return cWithKeyword_2_0; }

		//testClassName=QName
		public Assignment getTestClassNameAssignment_2_1() { return cTestClassNameAssignment_2_1; }

		//QName
		public RuleCall getTestClassNameQNameParserRuleCall_2_1_0() { return cTestClassNameQNameParserRuleCall_2_1_0; }

		//description=STRING?
		public Assignment getDescriptionAssignment_3() { return cDescriptionAssignment_3; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_3_0() { return cDescriptionSTRINGTerminalRuleCall_3_0; }

		//("@" url=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"@"
		public Keyword getCommercialAtKeyword_4_0() { return cCommercialAtKeyword_4_0; }

		//url=STRING
		public Assignment getUrlAssignment_4_1() { return cUrlAssignment_4_1; }

		//STRING
		public RuleCall getUrlSTRINGTerminalRuleCall_4_1_0() { return cUrlSTRINGTerminalRuleCall_4_1_0; }

		//importSection=XImportSection?
		public Assignment getImportSectionAssignment_5() { return cImportSectionAssignment_5; }

		//XImportSection
		public RuleCall getImportSectionXImportSectionParserRuleCall_5_0() { return cImportSectionXImportSectionParserRuleCall_5_0; }

		//(("instance" | "val") instances+=Instance ("," instances+=Instance)* | stateFunctions+=StateFunction |
		//testSequences+=JexTestSequence | methods+=Method)*
		public Alternatives getAlternatives_6() { return cAlternatives_6; }

		//("instance" | "val") instances+=Instance ("," instances+=Instance)*
		public Group getGroup_6_0() { return cGroup_6_0; }

		//"instance" | "val"
		public Alternatives getAlternatives_6_0_0() { return cAlternatives_6_0_0; }

		//"instance"
		public Keyword getInstanceKeyword_6_0_0_0() { return cInstanceKeyword_6_0_0_0; }

		//"val"
		public Keyword getValKeyword_6_0_0_1() { return cValKeyword_6_0_0_1; }

		//instances+=Instance
		public Assignment getInstancesAssignment_6_0_1() { return cInstancesAssignment_6_0_1; }

		//Instance
		public RuleCall getInstancesInstanceParserRuleCall_6_0_1_0() { return cInstancesInstanceParserRuleCall_6_0_1_0; }

		//("," instances+=Instance)*
		public Group getGroup_6_0_2() { return cGroup_6_0_2; }

		//","
		public Keyword getCommaKeyword_6_0_2_0() { return cCommaKeyword_6_0_2_0; }

		//instances+=Instance
		public Assignment getInstancesAssignment_6_0_2_1() { return cInstancesAssignment_6_0_2_1; }

		//Instance
		public RuleCall getInstancesInstanceParserRuleCall_6_0_2_1_0() { return cInstancesInstanceParserRuleCall_6_0_2_1_0; }

		//stateFunctions+=StateFunction
		public Assignment getStateFunctionsAssignment_6_1() { return cStateFunctionsAssignment_6_1; }

		//StateFunction
		public RuleCall getStateFunctionsStateFunctionParserRuleCall_6_1_0() { return cStateFunctionsStateFunctionParserRuleCall_6_1_0; }

		//testSequences+=JexTestSequence
		public Assignment getTestSequencesAssignment_6_2() { return cTestSequencesAssignment_6_2; }

		//JexTestSequence
		public RuleCall getTestSequencesJexTestSequenceParserRuleCall_6_2_0() { return cTestSequencesJexTestSequenceParserRuleCall_6_2_0; }

		//methods+=Method
		public Assignment getMethodsAssignment_6_3() { return cMethodsAssignment_6_3; }

		//Method
		public RuleCall getMethodsMethodParserRuleCall_6_3_0() { return cMethodsMethodParserRuleCall_6_3_0; }
	}

	public class InstanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Instance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeJvmParameterizedTypeReferenceParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cExprAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cExprXExpressionParserRuleCall_2_1_0 = (RuleCall)cExprAssignment_2_1.eContents().get(0);
		
		//Instance:
		//	type=JvmParameterizedTypeReference? name=ID ("=" expr=XExpression)?;
		public ParserRule getRule() { return rule; }

		//type=JvmParameterizedTypeReference? name=ID ("=" expr=XExpression)?
		public Group getGroup() { return cGroup; }

		//type=JvmParameterizedTypeReference?
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//JvmParameterizedTypeReference
		public RuleCall getTypeJvmParameterizedTypeReferenceParserRuleCall_0_0() { return cTypeJvmParameterizedTypeReferenceParserRuleCall_0_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("=" expr=XExpression)?
		public Group getGroup_2() { return cGroup_2; }

		//"="
		public Keyword getEqualsSignKeyword_2_0() { return cEqualsSignKeyword_2_0; }

		//expr=XExpression
		public Assignment getExprAssignment_2_1() { return cExprAssignment_2_1; }

		//XExpression
		public RuleCall getExprXExpressionParserRuleCall_2_1_0() { return cExprXExpressionParserRuleCall_2_1_0; }
	}

	public class StateTestContextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StateTestContext");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStateFunctionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cJexTestSequenceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//StateTestContext:
		//	StateFunction | JexTestSequence;
		public ParserRule getRule() { return rule; }

		//StateFunction | JexTestSequence
		public Alternatives getAlternatives() { return cAlternatives; }

		//StateFunction
		public RuleCall getStateFunctionParserRuleCall_0() { return cStateFunctionParserRuleCall_0; }

		//JexTestSequence
		public RuleCall getJexTestSequenceParserRuleCall_1() { return cJexTestSequenceParserRuleCall_1; }
	}

	public class PropertiesTestOwnerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PropertiesTestOwner");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStateFunctionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cObjectTestParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//PropertiesTestOwner:
		//	StateFunction | ObjectTest;
		public ParserRule getRule() { return rule; }

		//StateFunction | ObjectTest
		public Alternatives getAlternatives() { return cAlternatives; }

		//StateFunction
		public RuleCall getStateFunctionParserRuleCall_0() { return cStateFunctionParserRuleCall_0; }

		//ObjectTest
		public RuleCall getObjectTestParserRuleCall_1() { return cObjectTestParserRuleCall_1; }
	}

	public class StateFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StateFunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMethodKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeJvmParameterizedTypeReferenceParserRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cParametersAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cParametersParameterParserRuleCall_6_0_0 = (RuleCall)cParametersAssignment_6_0.eContents().get(0);
		private final Group cGroup_6_1 = (Group)cGroup_6.eContents().get(1);
		private final Keyword cCommaKeyword_6_1_0 = (Keyword)cGroup_6_1.eContents().get(0);
		private final Assignment cParametersAssignment_6_1_1 = (Assignment)cGroup_6_1.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_6_1_1_0 = (RuleCall)cParametersAssignment_6_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTestAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTestPropertiesTestParserRuleCall_8_0 = (RuleCall)cTestAssignment_8.eContents().get(0);
		
		//StateFunction:
		//	"state" "method" type=JvmParameterizedTypeReference? name=ID description=STRING? "(" (parameters+=Parameter (","
		//	parameters+=Parameter)*)? ")" test=PropertiesTest;
		public ParserRule getRule() { return rule; }

		//"state" "method" type=JvmParameterizedTypeReference? name=ID description=STRING? "(" (parameters+=Parameter (","
		//parameters+=Parameter)*)? ")" test=PropertiesTest
		public Group getGroup() { return cGroup; }

		//"state"
		public Keyword getStateKeyword_0() { return cStateKeyword_0; }

		//"method"
		public Keyword getMethodKeyword_1() { return cMethodKeyword_1; }

		//type=JvmParameterizedTypeReference?
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }

		//JvmParameterizedTypeReference
		public RuleCall getTypeJvmParameterizedTypeReferenceParserRuleCall_2_0() { return cTypeJvmParameterizedTypeReferenceParserRuleCall_2_0; }

		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }

		//description=STRING?
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_0() { return cDescriptionSTRINGTerminalRuleCall_4_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }

		//(parameters+=Parameter ("," parameters+=Parameter)*)?
		public Group getGroup_6() { return cGroup_6; }

		//parameters+=Parameter
		public Assignment getParametersAssignment_6_0() { return cParametersAssignment_6_0; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_6_0_0() { return cParametersParameterParserRuleCall_6_0_0; }

		//("," parameters+=Parameter)*
		public Group getGroup_6_1() { return cGroup_6_1; }

		//","
		public Keyword getCommaKeyword_6_1_0() { return cCommaKeyword_6_1_0; }

		//parameters+=Parameter
		public Assignment getParametersAssignment_6_1_1() { return cParametersAssignment_6_1_1; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_6_1_1_0() { return cParametersParameterParserRuleCall_6_1_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }

		//test=PropertiesTest
		public Assignment getTestAssignment_8() { return cTestAssignment_8; }

		//PropertiesTest
		public RuleCall getTestPropertiesTestParserRuleCall_8_0() { return cTestPropertiesTestParserRuleCall_8_0; }
	}

	public class JexTestSequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JexTestSequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSequenceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDescriptionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_2_0 = (RuleCall)cDescriptionAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cInstanceKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cValKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Assignment cInstancesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cInstancesInstanceParserRuleCall_4_1_0 = (RuleCall)cInstancesAssignment_4_1.eContents().get(0);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Keyword cCommaKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Assignment cInstancesAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final RuleCall cInstancesInstanceParserRuleCall_4_2_1_0 = (RuleCall)cInstancesAssignment_4_2_1.eContents().get(0);
		private final Assignment cTransitionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTransitionsTransitionParserRuleCall_5_0 = (RuleCall)cTransitionsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//JexTestSequence:
		//	"sequence" name=ID description=STRING? "{" (("instance" | "val") instances+=Instance ("," instances+=Instance)*)*
		//	transitions+=Transition* "}";
		public ParserRule getRule() { return rule; }

		//"sequence" name=ID description=STRING? "{" (("instance" | "val") instances+=Instance ("," instances+=Instance)*)*
		//transitions+=Transition* "}"
		public Group getGroup() { return cGroup; }

		//"sequence"
		public Keyword getSequenceKeyword_0() { return cSequenceKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//description=STRING?
		public Assignment getDescriptionAssignment_2() { return cDescriptionAssignment_2; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_2_0() { return cDescriptionSTRINGTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//(("instance" | "val") instances+=Instance ("," instances+=Instance)*)*
		public Group getGroup_4() { return cGroup_4; }

		//"instance" | "val"
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }

		//"instance"
		public Keyword getInstanceKeyword_4_0_0() { return cInstanceKeyword_4_0_0; }

		//"val"
		public Keyword getValKeyword_4_0_1() { return cValKeyword_4_0_1; }

		//instances+=Instance
		public Assignment getInstancesAssignment_4_1() { return cInstancesAssignment_4_1; }

		//Instance
		public RuleCall getInstancesInstanceParserRuleCall_4_1_0() { return cInstancesInstanceParserRuleCall_4_1_0; }

		//("," instances+=Instance)*
		public Group getGroup_4_2() { return cGroup_4_2; }

		//","
		public Keyword getCommaKeyword_4_2_0() { return cCommaKeyword_4_2_0; }

		//instances+=Instance
		public Assignment getInstancesAssignment_4_2_1() { return cInstancesAssignment_4_2_1; }

		//Instance
		public RuleCall getInstancesInstanceParserRuleCall_4_2_1_0() { return cInstancesInstanceParserRuleCall_4_2_1_0; }

		//transitions+=Transition*
		public Assignment getTransitionsAssignment_5() { return cTransitionsAssignment_5; }

		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_5_0() { return cTransitionsTransitionParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class QNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QName:
		//	ID+ ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID+ ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID+
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStateAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cNumberSignKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cNameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_2_1_0 = (RuleCall)cNameAssignment_2_1.eContents().get(0);
		private final Assignment cDescriptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_3_0 = (RuleCall)cDescriptionAssignment_3.eContents().get(0);
		private final Assignment cObjectTestsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cObjectTestsObjectTestParserRuleCall_4_0 = (RuleCall)cObjectTestsAssignment_4.eContents().get(0);
		
		//State:
		//	{State} "state" ("#" name=ID)? description=STRING? objectTests+=ObjectTest+;
		public ParserRule getRule() { return rule; }

		//{State} "state" ("#" name=ID)? description=STRING? objectTests+=ObjectTest+
		public Group getGroup() { return cGroup; }

		//{State}
		public Action getStateAction_0() { return cStateAction_0; }

		//"state"
		public Keyword getStateKeyword_1() { return cStateKeyword_1; }

		//("#" name=ID)?
		public Group getGroup_2() { return cGroup_2; }

		//"#"
		public Keyword getNumberSignKeyword_2_0() { return cNumberSignKeyword_2_0; }

		//name=ID
		public Assignment getNameAssignment_2_1() { return cNameAssignment_2_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_1_0() { return cNameIDTerminalRuleCall_2_1_0; }

		//description=STRING?
		public Assignment getDescriptionAssignment_3() { return cDescriptionAssignment_3; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_3_0() { return cDescriptionSTRINGTerminalRuleCall_3_0; }

		//objectTests+=ObjectTest+
		public Assignment getObjectTestsAssignment_4() { return cObjectTestsAssignment_4; }

		//ObjectTest
		public RuleCall getObjectTestsObjectTestParserRuleCall_4_0() { return cObjectTestsObjectTestParserRuleCall_4_0; }
	}

	public class ObjectTestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectTest");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cInstanceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cInstanceInstanceCrossReference_0_0 = (CrossReference)cInstanceAssignment_0.eContents().get(0);
		private final RuleCall cInstanceInstanceIDTerminalRuleCall_0_0_1 = (RuleCall)cInstanceInstanceCrossReference_0_0.eContents().get(1);
		private final Assignment cTestAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTestPropertiesTestParserRuleCall_1_0 = (RuleCall)cTestAssignment_1.eContents().get(0);
		
		//ObjectTest:
		//	instance=[Instance]? test=PropertiesTest;
		public ParserRule getRule() { return rule; }

		//instance=[Instance]? test=PropertiesTest
		public Group getGroup() { return cGroup; }

		//instance=[Instance]?
		public Assignment getInstanceAssignment_0() { return cInstanceAssignment_0; }

		//[Instance]
		public CrossReference getInstanceInstanceCrossReference_0_0() { return cInstanceInstanceCrossReference_0_0; }

		//ID
		public RuleCall getInstanceInstanceIDTerminalRuleCall_0_0_1() { return cInstanceInstanceIDTerminalRuleCall_0_0_1; }

		//test=PropertiesTest
		public Assignment getTestAssignment_1() { return cTestAssignment_1; }

		//PropertiesTest
		public RuleCall getTestPropertiesTestParserRuleCall_1_0() { return cTestPropertiesTestParserRuleCall_1_0; }
	}

	public class PropertiesTestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PropertiesTest");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPropertiesTestAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Assignment cExpressionsAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cExpressionsXExpressionParserRuleCall_1_1_0_0 = (RuleCall)cExpressionsAssignment_1_1_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//PropertiesTest returns xbase::XBlockExpression:
		//	{PropertiesTest} //	('=' stateFunctionCall = StateFunctionCall (';' | ('{' (expressions += XExpression ';')* '}'))) |
		//	("{" (expressions+=XExpression ";"?)* "}");
		public ParserRule getRule() { return rule; }

		//{PropertiesTest} //	('=' stateFunctionCall = StateFunctionCall (';' | ('{' (expressions += XExpression ';')* '}'))) |
		//("{" (expressions+=XExpression ";"?)* "}")
		public Group getGroup() { return cGroup; }

		//{PropertiesTest}
		public Action getPropertiesTestAction_0() { return cPropertiesTestAction_0; }

		//"{" (expressions+=XExpression ";"?)* "}"
		public Group getGroup_1() { return cGroup_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1_0() { return cLeftCurlyBracketKeyword_1_0; }

		//(expressions+=XExpression ";"?)*
		public Group getGroup_1_1() { return cGroup_1_1; }

		//expressions+=XExpression
		public Assignment getExpressionsAssignment_1_1_0() { return cExpressionsAssignment_1_1_0; }

		//XExpression
		public RuleCall getExpressionsXExpressionParserRuleCall_1_1_0_0() { return cExpressionsXExpressionParserRuleCall_1_1_0_0; }

		//";"?
		public Keyword getSemicolonKeyword_1_1_1() { return cSemicolonKeyword_1_1_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_1_2() { return cRightCurlyBracketKeyword_1_2; }
	}

	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Transition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cSourceAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cSourceTransitionSourceParserRuleCall_0_0_0 = (RuleCall)cSourceAssignment_0_0.eContents().get(0);
		private final Assignment cDescriptionAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_0_1_0 = (RuleCall)cDescriptionAssignment_0_1.eContents().get(0);
		private final Keyword cHyphenMinusHyphenMinusKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cActionsAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cActionsTransitionActionParserRuleCall_0_3_0 = (RuleCall)cActionsAssignment_0_3.eContents().get(0);
		private final Group cGroup_0_4 = (Group)cGroup_0.eContents().get(4);
		private final Keyword cCommaKeyword_0_4_0 = (Keyword)cGroup_0_4.eContents().get(0);
		private final Assignment cActionsAssignment_0_4_1 = (Assignment)cGroup_0_4.eContents().get(1);
		private final RuleCall cActionsTransitionActionParserRuleCall_0_4_1_0 = (RuleCall)cActionsAssignment_0_4_1.eContents().get(0);
		private final Assignment cEffectAssignment_0_5 = (Assignment)cGroup_0.eContents().get(5);
		private final RuleCall cEffectTransitionEffectParserRuleCall_0_5_0 = (RuleCall)cEffectAssignment_0_5.eContents().get(0);
		private final Assignment cEffectAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cEffectTransitionTargetEffectParserRuleCall_1_0 = (RuleCall)cEffectAssignment_1.eContents().get(0);
		
		////StateFunctionCall returns xbase::XBlockExpression:
		////	{StateFunctionCall}
		////	stateFunction = [StateFunction | ID]
		////	('(' (expressions += XExpression (',' expressions += XExpression)*)? ')')?
		////;
		//Transition:
		//	source=TransitionSource? // optional source
		//	// action part
		//	description=STRING? "--" actions+=TransitionAction ("," actions+=TransitionAction)* // effect part
		//	effect=TransitionEffect | // initial state
		//	effect=TransitionTargetEffect;
		public ParserRule getRule() { return rule; }

		//source=TransitionSource? // optional source
		//// action part
		//description=STRING? "--" actions+=TransitionAction ("," actions+=TransitionAction)* // effect part
		//effect=TransitionEffect | // initial state
		//effect=TransitionTargetEffect
		public Alternatives getAlternatives() { return cAlternatives; }

		//source=TransitionSource? // optional source
		//// action part
		//description=STRING? "--" actions+=TransitionAction ("," actions+=TransitionAction)* // effect part
		//effect=TransitionEffect
		public Group getGroup_0() { return cGroup_0; }

		//source=TransitionSource?
		public Assignment getSourceAssignment_0_0() { return cSourceAssignment_0_0; }

		//TransitionSource
		public RuleCall getSourceTransitionSourceParserRuleCall_0_0_0() { return cSourceTransitionSourceParserRuleCall_0_0_0; }

		//description=STRING?
		public Assignment getDescriptionAssignment_0_1() { return cDescriptionAssignment_0_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_0_1_0() { return cDescriptionSTRINGTerminalRuleCall_0_1_0; }

		//"--"
		public Keyword getHyphenMinusHyphenMinusKeyword_0_2() { return cHyphenMinusHyphenMinusKeyword_0_2; }

		//actions+=TransitionAction
		public Assignment getActionsAssignment_0_3() { return cActionsAssignment_0_3; }

		//TransitionAction
		public RuleCall getActionsTransitionActionParserRuleCall_0_3_0() { return cActionsTransitionActionParserRuleCall_0_3_0; }

		//("," actions+=TransitionAction)*
		public Group getGroup_0_4() { return cGroup_0_4; }

		//","
		public Keyword getCommaKeyword_0_4_0() { return cCommaKeyword_0_4_0; }

		//actions+=TransitionAction
		public Assignment getActionsAssignment_0_4_1() { return cActionsAssignment_0_4_1; }

		//TransitionAction
		public RuleCall getActionsTransitionActionParserRuleCall_0_4_1_0() { return cActionsTransitionActionParserRuleCall_0_4_1_0; }

		//effect=TransitionEffect
		public Assignment getEffectAssignment_0_5() { return cEffectAssignment_0_5; }

		//TransitionEffect
		public RuleCall getEffectTransitionEffectParserRuleCall_0_5_0() { return cEffectTransitionEffectParserRuleCall_0_5_0; }

		//// initial state
		//effect=TransitionTargetEffect
		public Assignment getEffectAssignment_1() { return cEffectAssignment_1; }

		//TransitionTargetEffect
		public RuleCall getEffectTransitionTargetEffectParserRuleCall_1_0() { return cEffectTransitionTargetEffectParserRuleCall_1_0; }
	}

	public class TransitionSourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TransitionSource");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cStateAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cStateStateParserRuleCall_0_0 = (RuleCall)cStateAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cNumberSignKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cStateRefAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cStateRefStateCrossReference_1_1_0 = (CrossReference)cStateRefAssignment_1_1.eContents().get(0);
		private final RuleCall cStateRefStateIDTerminalRuleCall_1_1_0_1 = (RuleCall)cStateRefStateCrossReference_1_1_0.eContents().get(1);
		
		//TransitionSource:
		//	state=State | "#" stateRef=[State];
		public ParserRule getRule() { return rule; }

		//state=State | "#" stateRef=[State]
		public Alternatives getAlternatives() { return cAlternatives; }

		//state=State
		public Assignment getStateAssignment_0() { return cStateAssignment_0; }

		//State
		public RuleCall getStateStateParserRuleCall_0_0() { return cStateStateParserRuleCall_0_0; }

		//"#" stateRef=[State]
		public Group getGroup_1() { return cGroup_1; }

		//"#"
		public Keyword getNumberSignKeyword_1_0() { return cNumberSignKeyword_1_0; }

		//stateRef=[State]
		public Assignment getStateRefAssignment_1_1() { return cStateRefAssignment_1_1; }

		//[State]
		public CrossReference getStateRefStateCrossReference_1_1_0() { return cStateRefStateCrossReference_1_1_0; }

		//ID
		public RuleCall getStateRefStateIDTerminalRuleCall_1_1_0_1() { return cStateRefStateIDTerminalRuleCall_1_1_0_1; }
	}

	public class TransitionActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TransitionAction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTransitionExpressionActionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTransitionInputActionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//TransitionAction:
		//	TransitionExpressionAction | TransitionInputAction;
		public ParserRule getRule() { return rule; }

		//TransitionExpressionAction | TransitionInputAction
		public Alternatives getAlternatives() { return cAlternatives; }

		//TransitionExpressionAction
		public RuleCall getTransitionExpressionActionParserRuleCall_0() { return cTransitionExpressionActionParserRuleCall_0; }

		//TransitionInputAction
		public RuleCall getTransitionInputActionParserRuleCall_1() { return cTransitionInputActionParserRuleCall_1; }
	}

	public class TransitionExpressionActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TransitionExpressionAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cExprAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cExprXExpressionParserRuleCall_0_0 = (RuleCall)cExprAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cNumberSignKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cTimesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cTimesXExpressionParserRuleCall_1_1_0 = (RuleCall)cTimesAssignment_1_1.eContents().get(0);
		
		//TransitionExpressionAction:
		//	expr=XExpression ("#" times=XExpression)?;
		public ParserRule getRule() { return rule; }

		//expr=XExpression ("#" times=XExpression)?
		public Group getGroup() { return cGroup; }

		//expr=XExpression
		public Assignment getExprAssignment_0() { return cExprAssignment_0; }

		//XExpression
		public RuleCall getExprXExpressionParserRuleCall_0_0() { return cExprXExpressionParserRuleCall_0_0; }

		//("#" times=XExpression)?
		public Group getGroup_1() { return cGroup_1; }

		//"#"
		public Keyword getNumberSignKeyword_1_0() { return cNumberSignKeyword_1_0; }

		//times=XExpression
		public Assignment getTimesAssignment_1_1() { return cTimesAssignment_1_1; }

		//XExpression
		public RuleCall getTimesXExpressionParserRuleCall_1_1_0() { return cTimesXExpressionParserRuleCall_1_1_0; }
	}

	public class TransitionInputActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TransitionInputAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInputKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cInputAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInputSTRINGTerminalRuleCall_1_0 = (RuleCall)cInputAssignment_1.eContents().get(0);
		
		//TransitionInputAction:
		//	"input" input=STRING;
		public ParserRule getRule() { return rule; }

		//"input" input=STRING
		public Group getGroup() { return cGroup; }

		//"input"
		public Keyword getInputKeyword_0() { return cInputKeyword_0; }

		//input=STRING
		public Assignment getInputAssignment_1() { return cInputAssignment_1; }

		//STRING
		public RuleCall getInputSTRINGTerminalRuleCall_1_0() { return cInputSTRINGTerminalRuleCall_1_0; }
	}

	public class TransitionEffectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TransitionEffect");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTransitionTargetEffectParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTransitionExceptionEffectParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTransitionOutputEffectParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//TransitionEffect:
		//	TransitionTargetEffect | TransitionExceptionEffect | TransitionOutputEffect;
		public ParserRule getRule() { return rule; }

		//TransitionTargetEffect | TransitionExceptionEffect | TransitionOutputEffect
		public Alternatives getAlternatives() { return cAlternatives; }

		//TransitionTargetEffect
		public RuleCall getTransitionTargetEffectParserRuleCall_0() { return cTransitionTargetEffectParserRuleCall_0; }

		//TransitionExceptionEffect
		public RuleCall getTransitionExceptionEffectParserRuleCall_1() { return cTransitionExceptionEffectParserRuleCall_1; }

		//TransitionOutputEffect
		public RuleCall getTransitionOutputEffectParserRuleCall_2() { return cTransitionOutputEffectParserRuleCall_2; }
	}

	public class TransitionTargetEffectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TransitionTargetEffect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusHyphenMinusGreaterThanSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cStateAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cStateStateParserRuleCall_1_0_0 = (RuleCall)cStateAssignment_1_0.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cNumberSignKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cStateRefAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final CrossReference cStateRefStateCrossReference_1_1_1_0 = (CrossReference)cStateRefAssignment_1_1_1.eContents().get(0);
		private final RuleCall cStateRefStateIDTerminalRuleCall_1_1_1_0_1 = (RuleCall)cStateRefStateCrossReference_1_1_1_0.eContents().get(1);
		
		//TransitionTargetEffect:
		//	"-->" (state=State | "#" stateRef=[State]);
		public ParserRule getRule() { return rule; }

		//"-->" (state=State | "#" stateRef=[State])
		public Group getGroup() { return cGroup; }

		//"-->"
		public Keyword getHyphenMinusHyphenMinusGreaterThanSignKeyword_0() { return cHyphenMinusHyphenMinusGreaterThanSignKeyword_0; }

		//state=State | "#" stateRef=[State]
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//state=State
		public Assignment getStateAssignment_1_0() { return cStateAssignment_1_0; }

		//State
		public RuleCall getStateStateParserRuleCall_1_0_0() { return cStateStateParserRuleCall_1_0_0; }

		//"#" stateRef=[State]
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"#"
		public Keyword getNumberSignKeyword_1_1_0() { return cNumberSignKeyword_1_1_0; }

		//stateRef=[State]
		public Assignment getStateRefAssignment_1_1_1() { return cStateRefAssignment_1_1_1; }

		//[State]
		public CrossReference getStateRefStateCrossReference_1_1_1_0() { return cStateRefStateCrossReference_1_1_1_0; }

		//ID
		public RuleCall getStateRefStateIDTerminalRuleCall_1_1_1_0_1() { return cStateRefStateIDTerminalRuleCall_1_1_1_0_1; }
	}

	public class TransitionExceptionEffectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TransitionExceptionEffect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cThrowsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cExceptionClassAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExceptionClassJvmParameterizedTypeReferenceParserRuleCall_1_0 = (RuleCall)cExceptionClassAssignment_1.eContents().get(0);
		
		//TransitionExceptionEffect:
		//	"throws" exceptionClass=JvmParameterizedTypeReference;
		public ParserRule getRule() { return rule; }

		//"throws" exceptionClass=JvmParameterizedTypeReference
		public Group getGroup() { return cGroup; }

		//"throws"
		public Keyword getThrowsKeyword_0() { return cThrowsKeyword_0; }

		//exceptionClass=JvmParameterizedTypeReference
		public Assignment getExceptionClassAssignment_1() { return cExceptionClassAssignment_1; }

		//JvmParameterizedTypeReference
		public RuleCall getExceptionClassJvmParameterizedTypeReferenceParserRuleCall_1_0() { return cExceptionClassJvmParameterizedTypeReferenceParserRuleCall_1_0; }
	}

	public class TransitionOutputEffectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TransitionOutputEffect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOutputsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPatternAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPatternSTRINGTerminalRuleCall_1_0 = (RuleCall)cPatternAssignment_1.eContents().get(0);
		
		//TransitionOutputEffect:
		//	"outputs" pattern=STRING;
		public ParserRule getRule() { return rule; }

		//"outputs" pattern=STRING
		public Group getGroup() { return cGroup; }

		//"outputs"
		public Keyword getOutputsKeyword_0() { return cOutputsKeyword_0; }

		//pattern=STRING
		public Assignment getPatternAssignment_1() { return cPatternAssignment_1; }

		//STRING
		public RuleCall getPatternSTRINGTerminalRuleCall_1_0() { return cPatternSTRINGTerminalRuleCall_1_0; }
	}

	public class MethodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Method");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStaticAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cStaticStaticKeyword_0_0 = (Keyword)cStaticAssignment_0.eContents().get(0);
		private final Keyword cMethodKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cReturnTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cReturnTypeJvmParameterizedTypeReferenceParserRuleCall_2_0 = (RuleCall)cReturnTypeAssignment_2.eContents().get(0);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Alternatives cNameAlternatives_3_0 = (Alternatives)cNameAssignment_3.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_3_0_0 = (RuleCall)cNameAlternatives_3_0.eContents().get(0);
		private final RuleCall cNameOpEqualityParserRuleCall_3_0_1 = (RuleCall)cNameAlternatives_3_0.eContents().get(1);
		private final RuleCall cNameOpCompareParserRuleCall_3_0_2 = (RuleCall)cNameAlternatives_3_0.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cParametersAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cParametersParameterParserRuleCall_5_0_0 = (RuleCall)cParametersAssignment_5_0.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Keyword cCommaKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cParametersAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_5_1_1_0 = (RuleCall)cParametersAssignment_5_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cBodyAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cBodyXExpressionParserRuleCall_7_0 = (RuleCall)cBodyAssignment_7.eContents().get(0);
		
		//Method:
		//	static?="static"? "method" returnType=JvmParameterizedTypeReference? name=(ID | OpEquality | OpCompare) "("
		//	(parameters+=Parameter ("," parameters+=Parameter)*)? ")" body=XExpression;
		public ParserRule getRule() { return rule; }

		//static?="static"? "method" returnType=JvmParameterizedTypeReference? name=(ID | OpEquality | OpCompare) "("
		//(parameters+=Parameter ("," parameters+=Parameter)*)? ")" body=XExpression
		public Group getGroup() { return cGroup; }

		//static?="static"?
		public Assignment getStaticAssignment_0() { return cStaticAssignment_0; }

		//"static"
		public Keyword getStaticStaticKeyword_0_0() { return cStaticStaticKeyword_0_0; }

		//"method"
		public Keyword getMethodKeyword_1() { return cMethodKeyword_1; }

		//returnType=JvmParameterizedTypeReference?
		public Assignment getReturnTypeAssignment_2() { return cReturnTypeAssignment_2; }

		//JvmParameterizedTypeReference
		public RuleCall getReturnTypeJvmParameterizedTypeReferenceParserRuleCall_2_0() { return cReturnTypeJvmParameterizedTypeReferenceParserRuleCall_2_0; }

		//name=(ID | OpEquality | OpCompare)
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//ID | OpEquality | OpCompare
		public Alternatives getNameAlternatives_3_0() { return cNameAlternatives_3_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0_0() { return cNameIDTerminalRuleCall_3_0_0; }

		//OpEquality
		public RuleCall getNameOpEqualityParserRuleCall_3_0_1() { return cNameOpEqualityParserRuleCall_3_0_1; }

		//OpCompare
		public RuleCall getNameOpCompareParserRuleCall_3_0_2() { return cNameOpCompareParserRuleCall_3_0_2; }

		//"("
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }

		//(parameters+=Parameter ("," parameters+=Parameter)*)?
		public Group getGroup_5() { return cGroup_5; }

		//parameters+=Parameter
		public Assignment getParametersAssignment_5_0() { return cParametersAssignment_5_0; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_5_0_0() { return cParametersParameterParserRuleCall_5_0_0; }

		//("," parameters+=Parameter)*
		public Group getGroup_5_1() { return cGroup_5_1; }

		//","
		public Keyword getCommaKeyword_5_1_0() { return cCommaKeyword_5_1_0; }

		//parameters+=Parameter
		public Assignment getParametersAssignment_5_1_1() { return cParametersAssignment_5_1_1; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_5_1_1_0() { return cParametersParameterParserRuleCall_5_1_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }

		//body=XExpression
		public Assignment getBodyAssignment_7() { return cBodyAssignment_7; }

		//XExpression
		public RuleCall getBodyXExpressionParserRuleCall_7_0() { return cBodyXExpressionParserRuleCall_7_0; }
	}

	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeJvmParameterizedTypeReferenceParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Parameter:
		//	type=JvmParameterizedTypeReference name=ID;
		public ParserRule getRule() { return rule; }

		//type=JvmParameterizedTypeReference name=ID
		public Group getGroup() { return cGroup; }

		//type=JvmParameterizedTypeReference
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//JvmParameterizedTypeReference
		public RuleCall getTypeJvmParameterizedTypeReferenceParserRuleCall_0_0() { return cTypeJvmParameterizedTypeReferenceParserRuleCall_0_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	
	
	private JexTestCaseElements pJexTestCase;
	private InstanceElements pInstance;
	private StateTestContextElements pStateTestContext;
	private PropertiesTestOwnerElements pPropertiesTestOwner;
	private StateFunctionElements pStateFunction;
	private JexTestSequenceElements pJexTestSequence;
	private QNameElements pQName;
	private StateElements pState;
	private ObjectTestElements pObjectTest;
	private PropertiesTestElements pPropertiesTest;
	private TransitionElements pTransition;
	private TransitionSourceElements pTransitionSource;
	private TransitionActionElements pTransitionAction;
	private TransitionExpressionActionElements pTransitionExpressionAction;
	private TransitionInputActionElements pTransitionInputAction;
	private TransitionEffectElements pTransitionEffect;
	private TransitionTargetEffectElements pTransitionTargetEffect;
	private TransitionExceptionEffectElements pTransitionExceptionEffect;
	private TransitionOutputEffectElements pTransitionOutputEffect;
	private MethodElements pMethod;
	private ParameterElements pParameter;
	
	private final Grammar grammar;

	private XbaseGrammarAccess gaXbase;

	@Inject
	public JexTestGrammarAccess(GrammarProvider grammarProvider,
		XbaseGrammarAccess gaXbase) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaXbase = gaXbase;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("no.hal.jex.jextest.JexTest".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public XbaseGrammarAccess getXbaseGrammarAccess() {
		return gaXbase;
	}

	
	//JexTestCase:
	//	"test" testedClass=JvmParameterizedTypeReference ("with" testClassName=QName)? description=STRING? ("@" url=STRING)?
	//	importSection=XImportSection? (("instance" | "val") instances+=Instance ("," instances+=Instance)* |
	//	stateFunctions+=StateFunction | testSequences+=JexTestSequence | methods+=Method)*;
	public JexTestCaseElements getJexTestCaseAccess() {
		return (pJexTestCase != null) ? pJexTestCase : (pJexTestCase = new JexTestCaseElements());
	}
	
	public ParserRule getJexTestCaseRule() {
		return getJexTestCaseAccess().getRule();
	}

	//Instance:
	//	type=JvmParameterizedTypeReference? name=ID ("=" expr=XExpression)?;
	public InstanceElements getInstanceAccess() {
		return (pInstance != null) ? pInstance : (pInstance = new InstanceElements());
	}
	
	public ParserRule getInstanceRule() {
		return getInstanceAccess().getRule();
	}

	//StateTestContext:
	//	StateFunction | JexTestSequence;
	public StateTestContextElements getStateTestContextAccess() {
		return (pStateTestContext != null) ? pStateTestContext : (pStateTestContext = new StateTestContextElements());
	}
	
	public ParserRule getStateTestContextRule() {
		return getStateTestContextAccess().getRule();
	}

	//PropertiesTestOwner:
	//	StateFunction | ObjectTest;
	public PropertiesTestOwnerElements getPropertiesTestOwnerAccess() {
		return (pPropertiesTestOwner != null) ? pPropertiesTestOwner : (pPropertiesTestOwner = new PropertiesTestOwnerElements());
	}
	
	public ParserRule getPropertiesTestOwnerRule() {
		return getPropertiesTestOwnerAccess().getRule();
	}

	//StateFunction:
	//	"state" "method" type=JvmParameterizedTypeReference? name=ID description=STRING? "(" (parameters+=Parameter (","
	//	parameters+=Parameter)*)? ")" test=PropertiesTest;
	public StateFunctionElements getStateFunctionAccess() {
		return (pStateFunction != null) ? pStateFunction : (pStateFunction = new StateFunctionElements());
	}
	
	public ParserRule getStateFunctionRule() {
		return getStateFunctionAccess().getRule();
	}

	//JexTestSequence:
	//	"sequence" name=ID description=STRING? "{" (("instance" | "val") instances+=Instance ("," instances+=Instance)*)*
	//	transitions+=Transition* "}";
	public JexTestSequenceElements getJexTestSequenceAccess() {
		return (pJexTestSequence != null) ? pJexTestSequence : (pJexTestSequence = new JexTestSequenceElements());
	}
	
	public ParserRule getJexTestSequenceRule() {
		return getJexTestSequenceAccess().getRule();
	}

	//QName:
	//	ID+ ("." ID)*;
	public QNameElements getQNameAccess() {
		return (pQName != null) ? pQName : (pQName = new QNameElements());
	}
	
	public ParserRule getQNameRule() {
		return getQNameAccess().getRule();
	}

	//State:
	//	{State} "state" ("#" name=ID)? description=STRING? objectTests+=ObjectTest+;
	public StateElements getStateAccess() {
		return (pState != null) ? pState : (pState = new StateElements());
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}

	//ObjectTest:
	//	instance=[Instance]? test=PropertiesTest;
	public ObjectTestElements getObjectTestAccess() {
		return (pObjectTest != null) ? pObjectTest : (pObjectTest = new ObjectTestElements());
	}
	
	public ParserRule getObjectTestRule() {
		return getObjectTestAccess().getRule();
	}

	//PropertiesTest returns xbase::XBlockExpression:
	//	{PropertiesTest} //	('=' stateFunctionCall = StateFunctionCall (';' | ('{' (expressions += XExpression ';')* '}'))) |
	//	("{" (expressions+=XExpression ";"?)* "}");
	public PropertiesTestElements getPropertiesTestAccess() {
		return (pPropertiesTest != null) ? pPropertiesTest : (pPropertiesTest = new PropertiesTestElements());
	}
	
	public ParserRule getPropertiesTestRule() {
		return getPropertiesTestAccess().getRule();
	}

	////StateFunctionCall returns xbase::XBlockExpression:
	////	{StateFunctionCall}
	////	stateFunction = [StateFunction | ID]
	////	('(' (expressions += XExpression (',' expressions += XExpression)*)? ')')?
	////;
	//Transition:
	//	source=TransitionSource? // optional source
	//	// action part
	//	description=STRING? "--" actions+=TransitionAction ("," actions+=TransitionAction)* // effect part
	//	effect=TransitionEffect | // initial state
	//	effect=TransitionTargetEffect;
	public TransitionElements getTransitionAccess() {
		return (pTransition != null) ? pTransition : (pTransition = new TransitionElements());
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}

	//TransitionSource:
	//	state=State | "#" stateRef=[State];
	public TransitionSourceElements getTransitionSourceAccess() {
		return (pTransitionSource != null) ? pTransitionSource : (pTransitionSource = new TransitionSourceElements());
	}
	
	public ParserRule getTransitionSourceRule() {
		return getTransitionSourceAccess().getRule();
	}

	//TransitionAction:
	//	TransitionExpressionAction | TransitionInputAction;
	public TransitionActionElements getTransitionActionAccess() {
		return (pTransitionAction != null) ? pTransitionAction : (pTransitionAction = new TransitionActionElements());
	}
	
	public ParserRule getTransitionActionRule() {
		return getTransitionActionAccess().getRule();
	}

	//TransitionExpressionAction:
	//	expr=XExpression ("#" times=XExpression)?;
	public TransitionExpressionActionElements getTransitionExpressionActionAccess() {
		return (pTransitionExpressionAction != null) ? pTransitionExpressionAction : (pTransitionExpressionAction = new TransitionExpressionActionElements());
	}
	
	public ParserRule getTransitionExpressionActionRule() {
		return getTransitionExpressionActionAccess().getRule();
	}

	//TransitionInputAction:
	//	"input" input=STRING;
	public TransitionInputActionElements getTransitionInputActionAccess() {
		return (pTransitionInputAction != null) ? pTransitionInputAction : (pTransitionInputAction = new TransitionInputActionElements());
	}
	
	public ParserRule getTransitionInputActionRule() {
		return getTransitionInputActionAccess().getRule();
	}

	//TransitionEffect:
	//	TransitionTargetEffect | TransitionExceptionEffect | TransitionOutputEffect;
	public TransitionEffectElements getTransitionEffectAccess() {
		return (pTransitionEffect != null) ? pTransitionEffect : (pTransitionEffect = new TransitionEffectElements());
	}
	
	public ParserRule getTransitionEffectRule() {
		return getTransitionEffectAccess().getRule();
	}

	//TransitionTargetEffect:
	//	"-->" (state=State | "#" stateRef=[State]);
	public TransitionTargetEffectElements getTransitionTargetEffectAccess() {
		return (pTransitionTargetEffect != null) ? pTransitionTargetEffect : (pTransitionTargetEffect = new TransitionTargetEffectElements());
	}
	
	public ParserRule getTransitionTargetEffectRule() {
		return getTransitionTargetEffectAccess().getRule();
	}

	//TransitionExceptionEffect:
	//	"throws" exceptionClass=JvmParameterizedTypeReference;
	public TransitionExceptionEffectElements getTransitionExceptionEffectAccess() {
		return (pTransitionExceptionEffect != null) ? pTransitionExceptionEffect : (pTransitionExceptionEffect = new TransitionExceptionEffectElements());
	}
	
	public ParserRule getTransitionExceptionEffectRule() {
		return getTransitionExceptionEffectAccess().getRule();
	}

	//TransitionOutputEffect:
	//	"outputs" pattern=STRING;
	public TransitionOutputEffectElements getTransitionOutputEffectAccess() {
		return (pTransitionOutputEffect != null) ? pTransitionOutputEffect : (pTransitionOutputEffect = new TransitionOutputEffectElements());
	}
	
	public ParserRule getTransitionOutputEffectRule() {
		return getTransitionOutputEffectAccess().getRule();
	}

	//Method:
	//	static?="static"? "method" returnType=JvmParameterizedTypeReference? name=(ID | OpEquality | OpCompare) "("
	//	(parameters+=Parameter ("," parameters+=Parameter)*)? ")" body=XExpression;
	public MethodElements getMethodAccess() {
		return (pMethod != null) ? pMethod : (pMethod = new MethodElements());
	}
	
	public ParserRule getMethodRule() {
		return getMethodAccess().getRule();
	}

	//Parameter:
	//	type=JvmParameterizedTypeReference name=ID;
	public ParameterElements getParameterAccess() {
		return (pParameter != null) ? pParameter : (pParameter = new ParameterElements());
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}

	//XExpression:
	//	XAssignment;
	public XbaseGrammarAccess.XExpressionElements getXExpressionAccess() {
		return gaXbase.getXExpressionAccess();
	}
	
	public ParserRule getXExpressionRule() {
		return getXExpressionAccess().getRule();
	}

	//XAssignment returns XExpression:
	//	{XAssignment} feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign value=XAssignment | XOrExpression
	//	(=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMultiAssign])
	//	rightOperand=XAssignment)?;
	public XbaseGrammarAccess.XAssignmentElements getXAssignmentAccess() {
		return gaXbase.getXAssignmentAccess();
	}
	
	public ParserRule getXAssignmentRule() {
		return getXAssignmentAccess().getRule();
	}

	//OpSingleAssign:
	//	"=";
	public XbaseGrammarAccess.OpSingleAssignElements getOpSingleAssignAccess() {
		return gaXbase.getOpSingleAssignAccess();
	}
	
	public ParserRule getOpSingleAssignRule() {
		return getOpSingleAssignAccess().getRule();
	}

	//OpMultiAssign:
	//	"+=" | "-=";
	public XbaseGrammarAccess.OpMultiAssignElements getOpMultiAssignAccess() {
		return gaXbase.getOpMultiAssignAccess();
	}
	
	public ParserRule getOpMultiAssignRule() {
		return getOpMultiAssignAccess().getRule();
	}

	//XOrExpression returns XExpression:
	//	XAndExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOr])
	//	rightOperand=XAndExpression)*;
	public XbaseGrammarAccess.XOrExpressionElements getXOrExpressionAccess() {
		return gaXbase.getXOrExpressionAccess();
	}
	
	public ParserRule getXOrExpressionRule() {
		return getXOrExpressionAccess().getRule();
	}

	//OpOr:
	//	"||";
	public XbaseGrammarAccess.OpOrElements getOpOrAccess() {
		return gaXbase.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}

	//XAndExpression returns XExpression:
	//	XEqualityExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAnd])
	//	rightOperand=XEqualityExpression)*;
	public XbaseGrammarAccess.XAndExpressionElements getXAndExpressionAccess() {
		return gaXbase.getXAndExpressionAccess();
	}
	
	public ParserRule getXAndExpressionRule() {
		return getXAndExpressionAccess().getRule();
	}

	//OpAnd:
	//	"&&";
	public XbaseGrammarAccess.OpAndElements getOpAndAccess() {
		return gaXbase.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}

	//XEqualityExpression returns XExpression:
	//	XRelationalExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpEquality])
	//	rightOperand=XRelationalExpression)*;
	public XbaseGrammarAccess.XEqualityExpressionElements getXEqualityExpressionAccess() {
		return gaXbase.getXEqualityExpressionAccess();
	}
	
	public ParserRule getXEqualityExpressionRule() {
		return getXEqualityExpressionAccess().getRule();
	}

	//OpEquality:
	//	"==" | "!=" | "===" | "!==";
	public XbaseGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaXbase.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}

	//XRelationalExpression returns XExpression:
	//	XOtherOperatorExpression (=> ({XInstanceOfExpression.expression=current} "instanceof") type=JvmTypeReference | =>
	//	({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpCompare])
	//	rightOperand=XOtherOperatorExpression)*;
	public XbaseGrammarAccess.XRelationalExpressionElements getXRelationalExpressionAccess() {
		return gaXbase.getXRelationalExpressionAccess();
	}
	
	public ParserRule getXRelationalExpressionRule() {
		return getXRelationalExpressionAccess().getRule();
	}

	//OpCompare:
	//	">=" | "<=" | ">" | "<";
	public XbaseGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaXbase.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}

	//XOtherOperatorExpression returns XExpression:
	//	XAdditiveExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOther])
	//	rightOperand=XAdditiveExpression)*;
	public XbaseGrammarAccess.XOtherOperatorExpressionElements getXOtherOperatorExpressionAccess() {
		return gaXbase.getXOtherOperatorExpressionAccess();
	}
	
	public ParserRule getXOtherOperatorExpressionRule() {
		return getXOtherOperatorExpressionAccess().getRule();
	}

	//OpOther:
	//	"->" | "..<" | ">" ".." | ".." | "=>" | ">" (=> (">" ">") | ">") | "<" (=> ("<" "<") | "<") | "<>" | "?:" | "<=>";
	public XbaseGrammarAccess.OpOtherElements getOpOtherAccess() {
		return gaXbase.getOpOtherAccess();
	}
	
	public ParserRule getOpOtherRule() {
		return getOpOtherAccess().getRule();
	}

	//XAdditiveExpression returns XExpression:
	//	XMultiplicativeExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAdd])
	//	rightOperand=XMultiplicativeExpression)*;
	public XbaseGrammarAccess.XAdditiveExpressionElements getXAdditiveExpressionAccess() {
		return gaXbase.getXAdditiveExpressionAccess();
	}
	
	public ParserRule getXAdditiveExpressionRule() {
		return getXAdditiveExpressionAccess().getRule();
	}

	//OpAdd:
	//	"+" | "-";
	public XbaseGrammarAccess.OpAddElements getOpAddAccess() {
		return gaXbase.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}

	//XMultiplicativeExpression returns XExpression:
	//	XUnaryOperation (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMulti])
	//	rightOperand=XUnaryOperation)*;
	public XbaseGrammarAccess.XMultiplicativeExpressionElements getXMultiplicativeExpressionAccess() {
		return gaXbase.getXMultiplicativeExpressionAccess();
	}
	
	public ParserRule getXMultiplicativeExpressionRule() {
		return getXMultiplicativeExpressionAccess().getRule();
	}

	//OpMulti:
	//	"*" | "**" | "/" | "%";
	public XbaseGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaXbase.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}

	//XUnaryOperation returns XExpression:
	//	{XUnaryOperation} feature=[types::JvmIdentifiableElement|OpUnary] operand=XUnaryOperation | XCastedExpression;
	public XbaseGrammarAccess.XUnaryOperationElements getXUnaryOperationAccess() {
		return gaXbase.getXUnaryOperationAccess();
	}
	
	public ParserRule getXUnaryOperationRule() {
		return getXUnaryOperationAccess().getRule();
	}

	//OpUnary:
	//	"!" | "-" | "+";
	public XbaseGrammarAccess.OpUnaryElements getOpUnaryAccess() {
		return gaXbase.getOpUnaryAccess();
	}
	
	public ParserRule getOpUnaryRule() {
		return getOpUnaryAccess().getRule();
	}

	//XCastedExpression returns XExpression:
	//	XMemberFeatureCall (=> ({XCastedExpression.target=current} "as") type=JvmTypeReference)*;
	public XbaseGrammarAccess.XCastedExpressionElements getXCastedExpressionAccess() {
		return gaXbase.getXCastedExpressionAccess();
	}
	
	public ParserRule getXCastedExpressionRule() {
		return getXCastedExpressionAccess().getRule();
	}

	//XMemberFeatureCall returns XExpression:
	//	XPrimaryExpression (=> ({XAssignment.assignable=current} ("." | explicitStatic?="::")
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign) value=XAssignment | =>
	//	({XMemberFeatureCall.memberCallTarget=current} ("." | nullSafe?="?." | explicitStatic?="::")) ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] (=> explicitOperationCall?="("
	//	(memberCallArguments+=XShortClosure | memberCallArguments+=XExpression ("," memberCallArguments+=XExpression)*)? ")")?
	//	memberCallArguments+=XClosure?)*;
	public XbaseGrammarAccess.XMemberFeatureCallElements getXMemberFeatureCallAccess() {
		return gaXbase.getXMemberFeatureCallAccess();
	}
	
	public ParserRule getXMemberFeatureCallRule() {
		return getXMemberFeatureCallAccess().getRule();
	}

	//XPrimaryExpression returns XExpression:
	//	XConstructorCall | XBlockExpression | XSwitchExpression | XFeatureCall | XLiteral | XIfExpression | XForLoopExpression
	//	| XWhileExpression | XDoWhileExpression | XThrowExpression | XReturnExpression | XTryCatchFinallyExpression |
	//	XParenthesizedExpression;
	public XbaseGrammarAccess.XPrimaryExpressionElements getXPrimaryExpressionAccess() {
		return gaXbase.getXPrimaryExpressionAccess();
	}
	
	public ParserRule getXPrimaryExpressionRule() {
		return getXPrimaryExpressionAccess().getRule();
	}

	//XLiteral returns XExpression:
	//	XCollectionLiteral | XClosure | XBooleanLiteral | XNumberLiteral | XNullLiteral | XStringLiteral | XTypeLiteral;
	public XbaseGrammarAccess.XLiteralElements getXLiteralAccess() {
		return gaXbase.getXLiteralAccess();
	}
	
	public ParserRule getXLiteralRule() {
		return getXLiteralAccess().getRule();
	}

	//XCollectionLiteral:
	//	XSetLiteral | XListLiteral;
	public XbaseGrammarAccess.XCollectionLiteralElements getXCollectionLiteralAccess() {
		return gaXbase.getXCollectionLiteralAccess();
	}
	
	public ParserRule getXCollectionLiteralRule() {
		return getXCollectionLiteralAccess().getRule();
	}

	//XSetLiteral:
	//	{XSetLiteral} "#" "{" (elements+=XExpression ("," elements+=XExpression)*)? "}";
	public XbaseGrammarAccess.XSetLiteralElements getXSetLiteralAccess() {
		return gaXbase.getXSetLiteralAccess();
	}
	
	public ParserRule getXSetLiteralRule() {
		return getXSetLiteralAccess().getRule();
	}

	//XListLiteral:
	//	{XListLiteral} "#" "[" (elements+=XExpression ("," elements+=XExpression)*)? "]";
	public XbaseGrammarAccess.XListLiteralElements getXListLiteralAccess() {
		return gaXbase.getXListLiteralAccess();
	}
	
	public ParserRule getXListLiteralRule() {
		return getXListLiteralAccess().getRule();
	}

	//XClosure returns XExpression:
	//	=> ({XClosure} "[") => ((declaredFormalParameters+=JvmFormalParameter (","
	//	declaredFormalParameters+=JvmFormalParameter)*)? explicitSyntax?="|")? expression=XExpressionInClosure "]";
	public XbaseGrammarAccess.XClosureElements getXClosureAccess() {
		return gaXbase.getXClosureAccess();
	}
	
	public ParserRule getXClosureRule() {
		return getXClosureAccess().getRule();
	}

	//XExpressionInClosure returns XExpression:
	//	{XBlockExpression} (expressions+=XExpressionInsideBlock ";"?)*;
	public XbaseGrammarAccess.XExpressionInClosureElements getXExpressionInClosureAccess() {
		return gaXbase.getXExpressionInClosureAccess();
	}
	
	public ParserRule getXExpressionInClosureRule() {
		return getXExpressionInClosureAccess().getRule();
	}

	//XShortClosure returns XExpression:
	//	=> ({XClosure} (declaredFormalParameters+=JvmFormalParameter ("," declaredFormalParameters+=JvmFormalParameter)*)?
	//	explicitSyntax?="|") expression=XExpression;
	public XbaseGrammarAccess.XShortClosureElements getXShortClosureAccess() {
		return gaXbase.getXShortClosureAccess();
	}
	
	public ParserRule getXShortClosureRule() {
		return getXShortClosureAccess().getRule();
	}

	//XParenthesizedExpression returns XExpression:
	//	"(" XExpression ")";
	public XbaseGrammarAccess.XParenthesizedExpressionElements getXParenthesizedExpressionAccess() {
		return gaXbase.getXParenthesizedExpressionAccess();
	}
	
	public ParserRule getXParenthesizedExpressionRule() {
		return getXParenthesizedExpressionAccess().getRule();
	}

	//XIfExpression returns XExpression:
	//	{XIfExpression} "if" "(" if=XExpression ")" then=XExpression ("else" else=XExpression)?;
	public XbaseGrammarAccess.XIfExpressionElements getXIfExpressionAccess() {
		return gaXbase.getXIfExpressionAccess();
	}
	
	public ParserRule getXIfExpressionRule() {
		return getXIfExpressionAccess().getRule();
	}

	//XSwitchExpression returns XExpression:
	//	{XSwitchExpression} "switch" (=> (localVarName=ValidID ":")? switch=XExpression | => ("(" localVarName=ValidID ":")
	//	switch=XExpression ")") "{" cases+=XCasePart+ ("default" ":" default=XExpression)? "}";
	public XbaseGrammarAccess.XSwitchExpressionElements getXSwitchExpressionAccess() {
		return gaXbase.getXSwitchExpressionAccess();
	}
	
	public ParserRule getXSwitchExpressionRule() {
		return getXSwitchExpressionAccess().getRule();
	}

	//XCasePart:
	//	typeGuard=JvmTypeReference? ("case" case=XExpression)? ":" then=XExpression;
	public XbaseGrammarAccess.XCasePartElements getXCasePartAccess() {
		return gaXbase.getXCasePartAccess();
	}
	
	public ParserRule getXCasePartRule() {
		return getXCasePartAccess().getRule();
	}

	//XForLoopExpression returns XExpression:
	//	{XForLoopExpression} "for" "(" declaredParam=JvmFormalParameter ":" forExpression=XExpression ")"
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XForLoopExpressionElements getXForLoopExpressionAccess() {
		return gaXbase.getXForLoopExpressionAccess();
	}
	
	public ParserRule getXForLoopExpressionRule() {
		return getXForLoopExpressionAccess().getRule();
	}

	//XWhileExpression returns XExpression:
	//	{XWhileExpression} "while" "(" predicate=XExpression ")" body=XExpression;
	public XbaseGrammarAccess.XWhileExpressionElements getXWhileExpressionAccess() {
		return gaXbase.getXWhileExpressionAccess();
	}
	
	public ParserRule getXWhileExpressionRule() {
		return getXWhileExpressionAccess().getRule();
	}

	//XDoWhileExpression returns XExpression:
	//	{XDoWhileExpression} "do" body=XExpression "while" "(" predicate=XExpression ")";
	public XbaseGrammarAccess.XDoWhileExpressionElements getXDoWhileExpressionAccess() {
		return gaXbase.getXDoWhileExpressionAccess();
	}
	
	public ParserRule getXDoWhileExpressionRule() {
		return getXDoWhileExpressionAccess().getRule();
	}

	//XBlockExpression returns XExpression:
	//	{XBlockExpression} "{" (expressions+=XExpressionInsideBlock ";"?)* "}";
	public XbaseGrammarAccess.XBlockExpressionElements getXBlockExpressionAccess() {
		return gaXbase.getXBlockExpressionAccess();
	}
	
	public ParserRule getXBlockExpressionRule() {
		return getXBlockExpressionAccess().getRule();
	}

	//XExpressionInsideBlock returns XExpression:
	//	XVariableDeclaration | XExpression;
	public XbaseGrammarAccess.XExpressionInsideBlockElements getXExpressionInsideBlockAccess() {
		return gaXbase.getXExpressionInsideBlockAccess();
	}
	
	public ParserRule getXExpressionInsideBlockRule() {
		return getXExpressionInsideBlockAccess().getRule();
	}

	//XVariableDeclaration returns XExpression:
	//	{XVariableDeclaration} (writeable?="var" | "val") (=> (type=JvmTypeReference name=ValidID) | name=ValidID) ("="
	//	right=XExpression)?;
	public XbaseGrammarAccess.XVariableDeclarationElements getXVariableDeclarationAccess() {
		return gaXbase.getXVariableDeclarationAccess();
	}
	
	public ParserRule getXVariableDeclarationRule() {
		return getXVariableDeclarationAccess().getRule();
	}

	//JvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference? name=ValidID;
	public XbaseGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaXbase.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}

	//FullJvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference name=ValidID;
	public XbaseGrammarAccess.FullJvmFormalParameterElements getFullJvmFormalParameterAccess() {
		return gaXbase.getFullJvmFormalParameterAccess();
	}
	
	public ParserRule getFullJvmFormalParameterRule() {
		return getFullJvmFormalParameterAccess().getRule();
	}

	//XFeatureCall returns XExpression:
	//	{XFeatureCall} ("<" typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|IdOrSuper] (=> explicitOperationCall?="(" (featureCallArguments+=XShortClosure
	//	| featureCallArguments+=XExpression ("," featureCallArguments+=XExpression)*)? ")")? featureCallArguments+=XClosure?;
	public XbaseGrammarAccess.XFeatureCallElements getXFeatureCallAccess() {
		return gaXbase.getXFeatureCallAccess();
	}
	
	public ParserRule getXFeatureCallRule() {
		return getXFeatureCallAccess().getRule();
	}

	//FeatureCallID:
	//	ValidID | "extends" | "static" | "import" | "extension";
	public XbaseGrammarAccess.FeatureCallIDElements getFeatureCallIDAccess() {
		return gaXbase.getFeatureCallIDAccess();
	}
	
	public ParserRule getFeatureCallIDRule() {
		return getFeatureCallIDAccess().getRule();
	}

	//IdOrSuper:
	//	FeatureCallID | "super";
	public XbaseGrammarAccess.IdOrSuperElements getIdOrSuperAccess() {
		return gaXbase.getIdOrSuperAccess();
	}
	
	public ParserRule getIdOrSuperRule() {
		return getIdOrSuperAccess().getRule();
	}

	//XConstructorCall returns XExpression:
	//	{XConstructorCall} "new" constructor=[types::JvmConstructor|QualifiedName] ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")? ("("
	//	(arguments+=XShortClosure | arguments+=XExpression ("," arguments+=XExpression)*)? ")")? arguments+=XClosure?;
	public XbaseGrammarAccess.XConstructorCallElements getXConstructorCallAccess() {
		return gaXbase.getXConstructorCallAccess();
	}
	
	public ParserRule getXConstructorCallRule() {
		return getXConstructorCallAccess().getRule();
	}

	//XBooleanLiteral returns XExpression:
	//	{XBooleanLiteral} ("false" | isTrue?="true");
	public XbaseGrammarAccess.XBooleanLiteralElements getXBooleanLiteralAccess() {
		return gaXbase.getXBooleanLiteralAccess();
	}
	
	public ParserRule getXBooleanLiteralRule() {
		return getXBooleanLiteralAccess().getRule();
	}

	//XNullLiteral returns XExpression:
	//	{XNullLiteral} "null";
	public XbaseGrammarAccess.XNullLiteralElements getXNullLiteralAccess() {
		return gaXbase.getXNullLiteralAccess();
	}
	
	public ParserRule getXNullLiteralRule() {
		return getXNullLiteralAccess().getRule();
	}

	//XNumberLiteral returns XExpression:
	//	{XNumberLiteral} value=Number;
	public XbaseGrammarAccess.XNumberLiteralElements getXNumberLiteralAccess() {
		return gaXbase.getXNumberLiteralAccess();
	}
	
	public ParserRule getXNumberLiteralRule() {
		return getXNumberLiteralAccess().getRule();
	}

	//XStringLiteral returns XExpression:
	//	{XStringLiteral} value=STRING;
	public XbaseGrammarAccess.XStringLiteralElements getXStringLiteralAccess() {
		return gaXbase.getXStringLiteralAccess();
	}
	
	public ParserRule getXStringLiteralRule() {
		return getXStringLiteralAccess().getRule();
	}

	//XTypeLiteral returns XExpression:
	//	{XTypeLiteral} "typeof" "(" type=[types::JvmType|QualifiedName] arrayDimensions+=ArrayBrackets* ")";
	public XbaseGrammarAccess.XTypeLiteralElements getXTypeLiteralAccess() {
		return gaXbase.getXTypeLiteralAccess();
	}
	
	public ParserRule getXTypeLiteralRule() {
		return getXTypeLiteralAccess().getRule();
	}

	//XThrowExpression returns XExpression:
	//	{XThrowExpression} "throw" expression=XExpression;
	public XbaseGrammarAccess.XThrowExpressionElements getXThrowExpressionAccess() {
		return gaXbase.getXThrowExpressionAccess();
	}
	
	public ParserRule getXThrowExpressionRule() {
		return getXThrowExpressionAccess().getRule();
	}

	//XReturnExpression returns XExpression:
	//	{XReturnExpression} "return" => expression=XExpression?;
	public XbaseGrammarAccess.XReturnExpressionElements getXReturnExpressionAccess() {
		return gaXbase.getXReturnExpressionAccess();
	}
	
	public ParserRule getXReturnExpressionRule() {
		return getXReturnExpressionAccess().getRule();
	}

	//XTryCatchFinallyExpression returns XExpression:
	//	{XTryCatchFinallyExpression} "try" expression=XExpression (catchClauses+=XCatchClause+ ("finally"
	//	finallyExpression=XExpression)? | "finally" finallyExpression=XExpression);
	public XbaseGrammarAccess.XTryCatchFinallyExpressionElements getXTryCatchFinallyExpressionAccess() {
		return gaXbase.getXTryCatchFinallyExpressionAccess();
	}
	
	public ParserRule getXTryCatchFinallyExpressionRule() {
		return getXTryCatchFinallyExpressionAccess().getRule();
	}

	//XCatchClause:
	//	"catch" "(" declaredParam=FullJvmFormalParameter ")" expression=XExpression;
	public XbaseGrammarAccess.XCatchClauseElements getXCatchClauseAccess() {
		return gaXbase.getXCatchClauseAccess();
	}
	
	public ParserRule getXCatchClauseRule() {
		return getXCatchClauseAccess().getRule();
	}

	//QualifiedName:
	//	ValidID ("." ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaXbase.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Number hidden():
	//	HEX | (INT | DECIMAL) ("." (INT | DECIMAL))?;
	public XbaseGrammarAccess.NumberElements getNumberAccess() {
		return gaXbase.getNumberAccess();
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	/// **
	// * Dummy rule, for "better" downwards compatibility, since GrammarAccess generates non-static inner classes, 
	// * which makes downstream grammars break on classloading, when a rule is removed.
	// * / StaticQualifier:
	//	(ValidID "::")+;
	public XbaseGrammarAccess.StaticQualifierElements getStaticQualifierAccess() {
		return gaXbase.getStaticQualifierAccess();
	}
	
	public ParserRule getStaticQualifierRule() {
		return getStaticQualifierAccess().getRule();
	}

	//terminal HEX:
	//	("0x" | "0X") ("0".."9" | "a".."f" | "A".."F" | "_")+ ("#" (("b" | "B") ("i" | "I") | ("l" | "L")))?;
	public TerminalRule getHEXRule() {
		return gaXbase.getHEXRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9" ("0".."9" | "_")*;
	public TerminalRule getINTRule() {
		return gaXbase.getINTRule();
	} 

	//terminal DECIMAL:
	//	INT (("e" | "E") ("+" | "-")? INT)? (("b" | "B") ("i" | "I" | "d" | "D") | ("l" | "L" | "d" | "D" | "f" | "F"))?;
	public TerminalRule getDECIMALRule() {
		return gaXbase.getDECIMALRule();
	} 

	//JvmTypeReference:
	//	JvmParameterizedTypeReference => ({JvmGenericArrayTypeReference.componentType=current} ArrayBrackets)* |
	//	XFunctionTypeRef;
	public XtypeGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaXbase.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}

	//ArrayBrackets:
	//	"[" "]";
	public XtypeGrammarAccess.ArrayBracketsElements getArrayBracketsAccess() {
		return gaXbase.getArrayBracketsAccess();
	}
	
	public ParserRule getArrayBracketsRule() {
		return getArrayBracketsAccess().getRule();
	}

	//XFunctionTypeRef:
	//	("(" (paramTypes+=JvmTypeReference ("," paramTypes+=JvmTypeReference)*)? ")")? "=>" returnType=JvmTypeReference;
	public XtypeGrammarAccess.XFunctionTypeRefElements getXFunctionTypeRefAccess() {
		return gaXbase.getXFunctionTypeRefAccess();
	}
	
	public ParserRule getXFunctionTypeRefRule() {
		return getXFunctionTypeRefAccess().getRule();
	}

	//JvmParameterizedTypeReference:
	//	type=[JvmType|QualifiedName] ("<" arguments+=JvmArgumentTypeReference ("," arguments+=JvmArgumentTypeReference)*
	//	">")?;
	public XtypeGrammarAccess.JvmParameterizedTypeReferenceElements getJvmParameterizedTypeReferenceAccess() {
		return gaXbase.getJvmParameterizedTypeReferenceAccess();
	}
	
	public ParserRule getJvmParameterizedTypeReferenceRule() {
		return getJvmParameterizedTypeReferenceAccess().getRule();
	}

	//JvmArgumentTypeReference returns JvmTypeReference:
	//	JvmTypeReference | JvmWildcardTypeReference;
	public XtypeGrammarAccess.JvmArgumentTypeReferenceElements getJvmArgumentTypeReferenceAccess() {
		return gaXbase.getJvmArgumentTypeReferenceAccess();
	}
	
	public ParserRule getJvmArgumentTypeReferenceRule() {
		return getJvmArgumentTypeReferenceAccess().getRule();
	}

	//JvmWildcardTypeReference:
	//	{JvmWildcardTypeReference} "?" (constraints+=JvmUpperBound | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmWildcardTypeReferenceElements getJvmWildcardTypeReferenceAccess() {
		return gaXbase.getJvmWildcardTypeReferenceAccess();
	}
	
	public ParserRule getJvmWildcardTypeReferenceRule() {
		return getJvmWildcardTypeReferenceAccess().getRule();
	}

	//JvmUpperBound:
	//	"extends" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundElements getJvmUpperBoundAccess() {
		return gaXbase.getJvmUpperBoundAccess();
	}
	
	public ParserRule getJvmUpperBoundRule() {
		return getJvmUpperBoundAccess().getRule();
	}

	//JvmUpperBoundAnded returns JvmUpperBound:
	//	"&" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundAndedElements getJvmUpperBoundAndedAccess() {
		return gaXbase.getJvmUpperBoundAndedAccess();
	}
	
	public ParserRule getJvmUpperBoundAndedRule() {
		return getJvmUpperBoundAndedAccess().getRule();
	}

	//JvmLowerBound:
	//	"super" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundElements getJvmLowerBoundAccess() {
		return gaXbase.getJvmLowerBoundAccess();
	}
	
	public ParserRule getJvmLowerBoundRule() {
		return getJvmLowerBoundAccess().getRule();
	}

	//JvmTypeParameter:
	//	name=ValidID (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded* | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmTypeParameterElements getJvmTypeParameterAccess() {
		return gaXbase.getJvmTypeParameterAccess();
	}
	
	public ParserRule getJvmTypeParameterRule() {
		return getJvmTypeParameterAccess().getRule();
	}

	//QualifiedNameWithWildcard:
	//	QualifiedName "." "*";
	public XtypeGrammarAccess.QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return gaXbase.getQualifiedNameWithWildcardAccess();
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}

	//ValidID:
	//	ID;
	public XtypeGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaXbase.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//XImportSection:
	//	importDeclarations+=XImportDeclaration+;
	public XtypeGrammarAccess.XImportSectionElements getXImportSectionAccess() {
		return gaXbase.getXImportSectionAccess();
	}
	
	public ParserRule getXImportSectionRule() {
		return getXImportSectionAccess().getRule();
	}

	//XImportDeclaration:
	//	"import" (static?="static" extension?="extension"? importedType=[JvmDeclaredType|QualifiedName] "." "*" |
	//	importedType=[JvmDeclaredType|QualifiedName] | importedNamespace=QualifiedNameWithWildcard) ";"?;
	public XtypeGrammarAccess.XImportDeclarationElements getXImportDeclarationAccess() {
		return gaXbase.getXImportDeclarationAccess();
	}
	
	public ParserRule getXImportDeclarationRule() {
		return getXImportDeclarationAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "$" | "_") ("a".."z" | "A".."Z" | "$" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaXbase.getIDRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaXbase.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaXbase.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaXbase.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaXbase.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaXbase.getANY_OTHERRule();
	} 
}
