/**
 * generated by Xtext
 */
package no.hal.jex.jextest.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.xbase.ui.labeling.XbaseLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class JexTestLabelProvider extends XbaseLabelProvider {
  @Inject
  public JexTestLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
