/**
 * generated by Xtext 2.9.1
 */
package no.hal.learning.exercise.xtext.ui;

import no.hal.learning.exercise.xtext.ui.AbstractXerciseUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XerciseUiModule extends AbstractXerciseUiModule {
  public XerciseUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
