<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="junit" nsURI="platform:/plugin/no.hal.learning.exercise.junit/model/junit-exercise.ecore"
    nsPrefix="junit">
  <eClassifiers xsi:type="ecore:EClass" name="JunitTestAnswer" eSuperTypes="../../no.hal.learning.exercise.model/model/exercise.ecore#//TaskAnswer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testRunName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JunitTestProposal">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../no.hal.learning.exercise.model/model/exercise.ecore#//TaskProposal">
      <eTypeArguments eClassifier="#//JunitTestAnswer"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JunitTestEvent" eSuperTypes="../../no.hal.learning.exercise.model/model/exercise.ecore#//TaskEvent">
    <eAnnotations source="exp4j">
      <details key="successRatio" value="successCount / (successCount + failureCount + errorCount)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="successCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="no.hal.learning.exercise.views.ExerciseView">
        <details key="dashes" value="- "/>
      </eAnnotations>
      <eAnnotations source="no.hal.emf.ui.parts.plot.IValueProvider">
        <details key="priority" value="3"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="no.hal.learning.exercise.views.ExerciseView">
        <details key="dashes" value="- . "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="no.hal.learning.exercise.views.ExerciseView">
        <details key="dashes" value=". "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
