/*
 * generated by Xtext
 */
package no.hal.emfs.xtext.ui.contentassist

import no.hal.emfs.xtext.ui.contentassist.AbstractXemfsProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XemfsProposalProvider extends AbstractXemfsProposalProvider {
}
