/**
 * generated by Xtext
 */
package no.hal.jex.jextest.validation;

import no.hal.jex.jextest.validation.AbstractJexTestValidator;
import org.eclipse.xtext.xbase.XExpression;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class JexTestValidator extends AbstractJexTestValidator {
  public void checkInnerExpressions(final XExpression expr) {
  }
}
