/*
 * generated by Xtext
 */
package no.hal.jex.jextest;

import org.eclipse.xtext.xbase.compiler.XbaseCompiler;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JexTestRuntimeModule extends no.hal.jex.jextest.AbstractJexTestRuntimeModule {

	public Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return no.hal.jex.jextest.jvmmodel.JexTestCompiler.class;
	}
}
