/*
 * generated by Xtext
 */
package no.hal.jex.jextest;

import org.eclipse.xtext.xbase.compiler.XbaseCompiler;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JexTestRuntimeModule extends no.hal.jex.jextest.AbstractJexTestRuntimeModule {

	public Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return no.hal.jex.jextest.jvmmodel.JexTestCompiler.class;
	}

	public Class<? extends org.eclipse.xtext.xbase.scoping.batch.ImplicitlyImportedTypes> bindImplicitlyImportedTypes() {
		return no.hal.jex.jextest.extensions.ImplicitlyImportedTypes.class;
	}
	
	public Class<? extends org.eclipse.xtext.xbase.scoping.featurecalls.OperatorMapping> bindOperatorMapping() {
		return no.hal.jex.jextest.extensions.OperatorMapping.class;
	}
}
