/**
 * generated by Xtext
 */
package no.hal.jex.jextest.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class JexTestQuickfixProvider extends XbaseQuickfixProvider {
}
