/*
 * generated by Xtext
 */
package no.hal.emfs.xtext.ui.contentassist

import no.hal.emfs.xtext.ui.contentassist.AbstractXemfsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XemfsProposalProvider extends AbstractXemfsProposalProvider {
}
