/*
 * generated by Xtext
 */
package no.hal.jex.jextest.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import no.hal.jex.jextest.ui.internal.JexTestActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JexTestExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JexTestActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JexTestActivator.getInstance().getInjector(JexTestActivator.NO_HAL_JEX_JEXTEST_JEXTEST);
	}
	
}
