/*
 * generated by Xtext 2.9.1
 */
package no.hal.learning.exercise.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractXerciseValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("platform:/plugin/no.hal.learning.exercise.model/model/exercise.ecore"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("platform:/plugin/no.hal.learning.exercise.junit/model/junit-exercise.ecore"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("platform:/plugin/no.hal.learning.exercise.jdt/model/jdt-exercise.ecore"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("platform:/plugin/no.hal.learning.exercise.workbench/model/workbench-exercise.ecore"));
		return result;
	}
	
}
