/**
 * generated by Xtext 2.9.1
 */
package no.hal.learning.exercise.xtext.ui.contentassist;

import no.hal.learning.exercise.xtext.ui.contentassist.AbstractXerciseProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class XerciseProposalProvider extends AbstractXerciseProposalProvider {
}
