/**
 * generated by Xtext
 */
package no.hal.emfs.xtext.serializer;

import no.hal.emfs.xtext.serializer.AbstractXemfsSyntacticSequencer;

@SuppressWarnings("all")
public class XemfsSyntacticSequencer extends AbstractXemfsSyntacticSequencer {
}
